import { SavedLocation } from '../types';

export interface GlobalCity {
  id: string;
  name: string;
  nameHi: string;
  nameEn: string;
  country: string;
  countryEn: string;
  countryCode: string;
  flag: string;
  region: string;
  regionEn: string;
  latitude: number;
  longitude: number;
  timezone: string;
  timezoneHours: number;
  type?: 'capital' | 'major' | 'pilgrimage' | 'metro';
}

export interface CountryInfo {
  code: string;
  nameHi: string;
  nameEn: string;
  flag: string;
  order: number;
}

export const GLOBAL_COUNTRIES: CountryInfo[] = [
  { code: 'IN', nameHi: 'भारत (India)', nameEn: 'India', flag: '🇮🇳', order: 1 },
  { code: 'US', nameHi: 'संयुक्त राज्य अमेरिका (USA)', nameEn: 'United States', flag: '🇺🇸', order: 2 },
  { code: 'GB', nameHi: 'यूनाइटेड किंगडम (UK)', nameEn: 'United Kingdom', flag: '🇬🇧', order: 3 },
  { code: 'CA', nameHi: 'कनाडा (Canada)', nameEn: 'Canada', flag: '🇨🇦', order: 4 },
  { code: 'AE', nameHi: 'संयुक्त अरब अमीरात (UAE)', nameEn: 'United Arab Emirates', flag: '🇦🇪', order: 5 },
  { code: 'AU', nameHi: 'ऑस्ट्रेलिया (Australia)', nameEn: 'Australia', flag: '🇦🇺', order: 6 },
  { code: 'NP', nameHi: 'नेपाल (Nepal)', nameEn: 'Nepal', flag: '🇳🇵', order: 7 },
  { code: 'MU', nameHi: 'मॉरीशस (Mauritius)', nameEn: 'Mauritius', flag: '🇲🇺', order: 8 },
  { code: 'SG', nameHi: 'सिंगापुर (Singapore)', nameEn: 'Singapore', flag: '🇸🇬', order: 9 },
  { code: 'MY', nameHi: 'मलेशिया (Malaysia)', nameEn: 'Malaysia', flag: '🇲🇾', order: 10 },
  { code: 'NZ', nameHi: 'न्यूजीलैंड (New Zealand)', nameEn: 'New Zealand', flag: '🇳🇿', order: 11 },
  { code: 'ZA', nameHi: 'दक्षिण अफ्रीका (South Africa)', nameEn: 'South Africa', flag: '🇿🇦', order: 12 },
  { code: 'FJ', nameHi: 'फिजी (Fiji)', nameEn: 'Fiji', flag: '🇫🇯', order: 13 },
  { code: 'QA', nameHi: 'कतर (Qatar)', nameEn: 'Qatar', flag: '🇶🇦', order: 14 },
  { code: 'SA', nameHi: 'सऊदी अरब (Saudi Arabia)', nameEn: 'Saudi Arabia', flag: '🇸🇦', order: 15 },
  { code: 'OM', nameHi: 'ओमान (Oman)', nameEn: 'Oman', flag: '🇴🇲', order: 16 },
  { code: 'KW', nameHi: 'कुवैत (Kuwait)', nameEn: 'Kuwait', flag: '🇰🇼', order: 17 },
  { code: 'BH', nameHi: 'बहरीन (Bahrain)', nameEn: 'Bahrain', flag: '🇧🇭', order: 18 },
  { code: 'DE', nameHi: 'जर्मनी (Germany)', nameEn: 'Germany', flag: '🇩🇪', order: 19 },
  { code: 'FR', nameHi: 'फ्रांस (France)', nameEn: 'France', flag: '🇫🇷', order: 20 },
  { code: 'NL', nameHi: 'नीदरलैंड (Netherlands)', nameEn: 'Netherlands', flag: '🇳🇱', order: 21 },
  { code: 'CH', nameHi: 'स्विट्जरलैंड (Switzerland)', nameEn: 'Switzerland', flag: '🇨🇭', order: 22 },
  { code: 'IE', nameHi: 'आयरलैंड (Ireland)', nameEn: 'Ireland', flag: '🇮🇪', order: 23 },
  { code: 'IT', nameHi: 'इटली (Italy)', nameEn: 'Italy', flag: '🇮🇹', order: 24 },
  { code: 'LK', nameHi: 'श्रीलंका (Sri Lanka)', nameEn: 'Sri Lanka', flag: '🇱🇰', order: 25 },
  { code: 'ID', nameHi: 'इंडोनेशिया / बाली (Indonesia)', nameEn: 'Indonesia', flag: '🇮🇩', order: 26 },
  { code: 'TH', nameHi: 'थाईलैंड (Thailand)', nameEn: 'Thailand', flag: '🇹🇭', order: 27 },
  { code: 'JP', nameHi: 'जापान (Japan)', nameEn: 'Japan', flag: '🇯🇵', order: 28 },
  { code: 'TT', nameHi: 'त्रिनिदाद और टोबैगो (Trinidad)', nameEn: 'Trinidad and Tobago', flag: '🇹🇹', order: 29 },
  { code: 'GY', nameHi: 'गुयाना (Guyana)', nameEn: 'Guyana', flag: '🇬🇾', order: 30 },
  { code: 'SR', nameHi: 'सूरीनाम (Suriname)', nameEn: 'Suriname', flag: '🇸🇷', order: 31 },
  { code: 'KE', nameHi: 'केन्या (Kenya)', nameEn: 'Kenya', flag: '🇰🇪', order: 32 },
  { code: 'RU', nameHi: 'रूस (Russia)', nameEn: 'Russia', flag: '🇷🇺', order: 33 },
];

export const GLOBAL_CITIES_DATABASE: GlobalCity[] = [
  // ==========================================
  // भारत (INDIA) - तीर्थ स्थल एवं प्रमुख महानगर
  // ==========================================
  {
    id: 'in-ujjain',
    name: 'उज्जैन (Ujjain)',
    nameHi: 'उज्जैन',
    nameEn: 'Ujjain',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'मध्य प्रदेश',
    regionEn: 'Madhya Pradesh',
    latitude: 23.1765,
    longitude: 75.7885,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-varanasi',
    name: 'वाराणसी / काशी (Varanasi)',
    nameHi: 'वाराणसी / काशी',
    nameEn: 'Varanasi / Kashi',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तर प्रदेश',
    regionEn: 'Uttar Pradesh',
    latitude: 25.3176,
    longitude: 82.9739,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-ayodhya',
    name: 'अयोध्या (Ayodhya)',
    nameHi: 'अयोध्या',
    nameEn: 'Ayodhya',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तर प्रदेश',
    regionEn: 'Uttar Pradesh',
    latitude: 26.7986,
    longitude: 82.1998,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-mathura',
    name: 'मथुरा (Mathura)',
    nameHi: 'मथुरा',
    nameEn: 'Mathura',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तर प्रदेश',
    regionEn: 'Uttar Pradesh',
    latitude: 27.4924,
    longitude: 77.6737,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-vrindavan',
    name: 'वृंदावन (Vrindavan)',
    nameHi: 'वृंदावन',
    nameEn: 'Vrindavan',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तर प्रदेश',
    regionEn: 'Uttar Pradesh',
    latitude: 27.5806,
    longitude: 77.7006,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-haridwar',
    name: 'हरिद्वार (Haridwar)',
    nameHi: 'हरिद्वार',
    nameEn: 'Haridwar',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तराखंड',
    regionEn: 'Uttarakhand',
    latitude: 29.9457,
    longitude: 78.1642,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-rishikesh',
    name: 'ऋषिकेश (Rishikesh)',
    nameHi: 'ऋषिकेश',
    nameEn: 'Rishikesh',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तराखंड',
    regionEn: 'Uttarakhand',
    latitude: 30.0869,
    longitude: 78.2676,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-badrinath',
    name: 'बद्रीनाथ (Badrinath)',
    nameHi: 'बद्रीनाथ',
    nameEn: 'Badrinath',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तराखंड',
    regionEn: 'Uttarakhand',
    latitude: 30.7433,
    longitude: 79.4938,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-kedarnath',
    name: 'केदारनाथ (Kedarnath)',
    nameHi: 'केदारनाथ',
    nameEn: 'Kedarnath',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तराखंड',
    regionEn: 'Uttarakhand',
    latitude: 30.7352,
    longitude: 79.0669,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-gangotri',
    name: 'गंगोत्री (Gangotri)',
    nameHi: 'गंगोत्री',
    nameEn: 'Gangotri',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तराखंड',
    regionEn: 'Uttarakhand',
    latitude: 30.994,
    longitude: 78.9398,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-yamunotri',
    name: 'यमुनोत्री (Yamunotri)',
    nameHi: 'यमुनोत्री',
    nameEn: 'Yamunotri',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तराखंड',
    regionEn: 'Uttarakhand',
    latitude: 31.014,
    longitude: 78.46,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-prayagraj',
    name: 'प्रयागराज (Prayagraj)',
    nameHi: 'प्रयागराज',
    nameEn: 'Prayagraj',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तर प्रदेश',
    regionEn: 'Uttar Pradesh',
    latitude: 25.4358,
    longitude: 81.8463,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-gaya',
    name: 'गया (Gaya)',
    nameHi: 'गया',
    nameEn: 'Gaya',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'बिहार',
    regionEn: 'Bihar',
    latitude: 24.7969,
    longitude: 85.0002,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-puri',
    name: 'पुरी जगन्नाथ (Puri)',
    nameHi: 'पुरी जगन्नाथ',
    nameEn: 'Puri',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'ओडिशा',
    regionEn: 'Odisha',
    latitude: 19.8135,
    longitude: 85.8312,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-dwarka',
    name: 'द्वारका (Dwarka)',
    nameHi: 'द्वारका',
    nameEn: 'Dwarka',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'गुजरात',
    regionEn: 'Gujarat',
    latitude: 22.2442,
    longitude: 68.9685,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-somnath',
    name: 'सोमनाथ (Somnath)',
    nameHi: 'सोमनाथ',
    nameEn: 'Somnath',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'गुजरात',
    regionEn: 'Gujarat',
    latitude: 20.888,
    longitude: 70.4012,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-rameswaram',
    name: 'रामेश्वरम (Rameswaram)',
    nameHi: 'रामेश्वरम',
    nameEn: 'Rameswaram',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'तमिलनाडु',
    regionEn: 'Tamil Nadu',
    latitude: 9.2876,
    longitude: 79.3129,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-tirupati',
    name: 'तिरुपति (Tirupati)',
    nameHi: 'तिरुपति',
    nameEn: 'Tirupati',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'आंध्र प्रदेश',
    regionEn: 'Andhra Pradesh',
    latitude: 13.6288,
    longitude: 79.4192,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-madurai',
    name: 'मदुरै (Madurai)',
    nameHi: 'मदुरै',
    nameEn: 'Madurai',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'तमिलनाडु',
    regionEn: 'Tamil Nadu',
    latitude: 9.9252,
    longitude: 78.1198,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-shirdi',
    name: 'शिरडी (Shirdi)',
    nameHi: 'शिरडी',
    nameEn: 'Shirdi',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'महाराष्ट्र',
    regionEn: 'Maharashtra',
    latitude: 19.766,
    longitude: 74.4774,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-omkareshwar',
    name: 'ओंकारेश्वर (Omkareshwar)',
    nameHi: 'ओंकारेश्वर',
    nameEn: 'Omkareshwar',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'मध्य प्रदेश',
    regionEn: 'Madhya Pradesh',
    latitude: 22.2455,
    longitude: 76.1511,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-vaishnodevi',
    name: 'कटरा / वैष्णो देवी (Katra / Vaishno Devi)',
    nameHi: 'कटरा / वैष्णो देवी',
    nameEn: 'Katra / Vaishno Devi',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'जम्मू और कश्मीर',
    regionEn: 'Jammu & Kashmir',
    latitude: 32.9904,
    longitude: 74.9318,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-delhi',
    name: 'नई दिल्ली (New Delhi)',
    nameHi: 'नई दिल्ली',
    nameEn: 'New Delhi',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'दिल्ली',
    regionEn: 'Delhi',
    latitude: 28.6139,
    longitude: 77.209,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'capital',
  },
  {
    id: 'in-mumbai',
    name: 'मुंबई (Mumbai)',
    nameHi: 'मुंबई',
    nameEn: 'Mumbai',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'महाराष्ट्र',
    regionEn: 'Maharashtra',
    latitude: 19.076,
    longitude: 72.8777,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'metro',
  },
  {
    id: 'in-kolkata',
    name: 'कोलकाता (Kolkata)',
    nameHi: 'कोलकाता',
    nameEn: 'Kolkata',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'पश्चिम बंगाल',
    regionEn: 'West Bengal',
    latitude: 22.5726,
    longitude: 88.3639,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'metro',
  },
  {
    id: 'in-chennai',
    name: 'चेन्नई (Chennai)',
    nameHi: 'चेन्नई',
    nameEn: 'Chennai',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'तमिलनाडु',
    regionEn: 'Tamil Nadu',
    latitude: 13.0827,
    longitude: 80.2707,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'metro',
  },
  {
    id: 'in-bengaluru',
    name: 'बेंगलुरु (Bengaluru)',
    nameHi: 'बेंगलुरु',
    nameEn: 'Bengaluru',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'कर्नाटक',
    regionEn: 'Karnataka',
    latitude: 12.9716,
    longitude: 77.5946,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'metro',
  },
  {
    id: 'in-hyderabad',
    name: 'हैदराबाद (Hyderabad)',
    nameHi: 'हैदराबाद',
    nameEn: 'Hyderabad',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'तेलंगाना',
    regionEn: 'Telangana',
    latitude: 17.385,
    longitude: 78.4867,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'metro',
  },
  {
    id: 'in-ahmedabad',
    name: 'अहमदाबाद (Ahmedabad)',
    nameHi: 'अहमदाबाद',
    nameEn: 'Ahmedabad',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'गुजरात',
    regionEn: 'Gujarat',
    latitude: 23.0225,
    longitude: 72.5714,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-surat',
    name: 'सूरत (Surat)',
    nameHi: 'सूरत',
    nameEn: 'Surat',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'गुजरात',
    regionEn: 'Gujarat',
    latitude: 21.1702,
    longitude: 72.8311,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-vadodara',
    name: 'वडोदरा (Vadodara)',
    nameHi: 'वडोदरा',
    nameEn: 'Vadodara',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'गुजरात',
    regionEn: 'Gujarat',
    latitude: 22.3072,
    longitude: 73.1812,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-pune',
    name: 'पुणे (Pune)',
    nameHi: 'पुणे',
    nameEn: 'Pune',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'महाराष्ट्र',
    regionEn: 'Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-nagpur',
    name: 'नागपुर (Nagpur)',
    nameHi: 'नागपुर',
    nameEn: 'Nagpur',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'महाराष्ट्र',
    regionEn: 'Maharashtra',
    latitude: 21.1458,
    longitude: 79.0882,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-jaipur',
    name: 'जयपुर (Jaipur)',
    nameHi: 'जयपुर',
    nameEn: 'Jaipur',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'राजस्थान',
    regionEn: 'Rajasthan',
    latitude: 26.9124,
    longitude: 75.7873,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-jodhpur',
    name: 'जोधपुर (Jodhpur)',
    nameHi: 'जोधपुर',
    nameEn: 'Jodhpur',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'राजस्थान',
    regionEn: 'Rajasthan',
    latitude: 26.2389,
    longitude: 73.0243,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-udaipur',
    name: 'उदयपुर (Udaipur)',
    nameHi: 'उदयपुर',
    nameEn: 'Udaipur',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'राजस्थान',
    regionEn: 'Rajasthan',
    latitude: 24.5854,
    longitude: 73.7125,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-bhopal',
    name: 'भोपाल (Bhopal)',
    nameHi: 'भोपाल',
    nameEn: 'Bhopal',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'मध्य प्रदेश',
    regionEn: 'Madhya Pradesh',
    latitude: 23.2599,
    longitude: 77.4126,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-indore',
    name: 'इन्दौर (Indore)',
    nameHi: 'इन्दौर',
    nameEn: 'Indore',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'मध्य प्रदेश',
    regionEn: 'Madhya Pradesh',
    latitude: 22.7196,
    longitude: 75.8577,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-gwalior',
    name: 'ग्वालियर (Gwalior)',
    nameHi: 'ग्वालियर',
    nameEn: 'Gwalior',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'मध्य प्रदेश',
    regionEn: 'Madhya Pradesh',
    latitude: 26.2183,
    longitude: 78.1828,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-jabalpur',
    name: 'जबलपुर (Jabalpur)',
    nameHi: 'जबलपुर',
    nameEn: 'Jabalpur',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'मध्य प्रदेश',
    regionEn: 'Madhya Pradesh',
    latitude: 23.1815,
    longitude: 79.9864,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-lucknow',
    name: 'लखनऊ (Lucknow)',
    nameHi: 'लखनऊ',
    nameEn: 'Lucknow',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तर प्रदेश',
    regionEn: 'Uttar Pradesh',
    latitude: 26.8467,
    longitude: 80.9462,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-kanpur',
    name: 'कानपुर (Kanpur)',
    nameHi: 'कानपुर',
    nameEn: 'Kanpur',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तर प्रदेश',
    regionEn: 'Uttar Pradesh',
    latitude: 26.4499,
    longitude: 80.3319,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-agra',
    name: 'आगरा (Agra)',
    nameHi: 'आगरा',
    nameEn: 'Agra',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तर प्रदेश',
    regionEn: 'Uttar Pradesh',
    latitude: 27.1767,
    longitude: 78.0081,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-noida',
    name: 'नोएडा (Noida)',
    nameHi: 'नोएडा',
    nameEn: 'Noida',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तर प्रदेश',
    regionEn: 'Uttar Pradesh',
    latitude: 28.5355,
    longitude: 77.391,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-patna',
    name: 'पटना (Patna)',
    nameHi: 'पटना',
    nameEn: 'Patna',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'बिहार',
    regionEn: 'Bihar',
    latitude: 25.5941,
    longitude: 85.1376,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-ranchi',
    name: 'राँची (Ranchi)',
    nameHi: 'राँची',
    nameEn: 'Ranchi',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'झारखंड',
    regionEn: 'Jharkhand',
    latitude: 23.3441,
    longitude: 85.3096,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-dehradun',
    name: 'देहरादून (Dehradun)',
    nameHi: 'देहरादून',
    nameEn: 'Dehradun',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'उत्तराखंड',
    regionEn: 'Uttarakhand',
    latitude: 30.3165,
    longitude: 78.0322,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-shimla',
    name: 'शिमला (Shimla)',
    nameHi: 'शिमला',
    nameEn: 'Shimla',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'हिमाचल प्रदेश',
    regionEn: 'Himachal Pradesh',
    latitude: 31.1048,
    longitude: 77.1734,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-chandigarh',
    name: 'चंडीगढ़ (Chandigarh)',
    nameHi: 'चंडीगढ़',
    nameEn: 'Chandigarh',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'पंजाब/हरियाणा',
    regionEn: 'Punjab/Haryana',
    latitude: 30.7333,
    longitude: 76.7794,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-amritsar',
    name: 'अमृतसर (Amritsar)',
    nameHi: 'अमृतसर',
    nameEn: 'Amritsar',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'पंजाब',
    regionEn: 'Punjab',
    latitude: 31.634,
    longitude: 74.8723,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-raipur',
    name: 'रायपुर (Raipur)',
    nameHi: 'रायपुर',
    nameEn: 'Raipur',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'छत्तीसगढ़',
    regionEn: 'Chhattisgarh',
    latitude: 21.2514,
    longitude: 81.6296,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-bhubaneswar',
    name: 'भुवनेश्वर (Bhubaneswar)',
    nameHi: 'भुवनेश्वर',
    nameEn: 'Bhubaneswar',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'ओडिशा',
    regionEn: 'Odisha',
    latitude: 20.2961,
    longitude: 85.8245,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },
  {
    id: 'in-guwahati',
    name: 'गुवाहाटी (Guwahati / Kamakhya)',
    nameHi: 'गुवाहाटी / कामाख्या',
    nameEn: 'Guwahati / Kamakhya',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'असम',
    regionEn: 'Assam',
    latitude: 26.1445,
    longitude: 91.7362,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'pilgrimage',
  },
  {
    id: 'in-panaji',
    name: 'पणजी (Panaji)',
    nameHi: 'पणजी',
    nameEn: 'Panaji',
    country: 'भारत',
    countryEn: 'India',
    countryCode: 'IN',
    flag: '🇮🇳',
    region: 'गोवा',
    regionEn: 'Goa',
    latitude: 15.4909,
    longitude: 73.8278,
    timezone: 'Asia/Kolkata',
    timezoneHours: 5.5,
    type: 'major',
  },

  // ========================================================
  // संयुक्त राज्य अमेरिका (UNITED STATES OF AMERICA - USA)
  // ========================================================
  {
    id: 'us-newyork',
    name: 'न्यू यॉर्क (New York City)',
    nameHi: 'न्यू यॉर्क',
    nameEn: 'New York City',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'न्यू यॉर्क (NY)',
    regionEn: 'New York',
    latitude: 40.7128,
    longitude: -74.006,
    timezone: 'America/New_York',
    timezoneHours: -5,
    type: 'metro',
  },
  {
    id: 'us-jerseycity',
    name: 'जर्सी सिटी (Jersey City)',
    nameHi: 'जर्सी सिटी',
    nameEn: 'Jersey City',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'न्यू जर्सी (NJ)',
    regionEn: 'New Jersey',
    latitude: 40.7178,
    longitude: -74.0431,
    timezone: 'America/New_York',
    timezoneHours: -5,
    type: 'major',
  },
  {
    id: 'us-edison',
    name: 'एडिसन (Edison)',
    nameHi: 'एडिसन',
    nameEn: 'Edison',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'न्यू जर्सी (NJ)',
    regionEn: 'New Jersey',
    latitude: 40.5187,
    longitude: -74.4121,
    timezone: 'America/New_York',
    timezoneHours: -5,
    type: 'major',
  },
  {
    id: 'us-sanjose',
    name: 'सैन जोस (San Jose)',
    nameHi: 'सैन जोस',
    nameEn: 'San Jose',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'कैलिफ़ोर्निया (CA)',
    regionEn: 'California',
    latitude: 37.3382,
    longitude: -121.8863,
    timezone: 'America/Los_Angeles',
    timezoneHours: -8,
    type: 'metro',
  },
  {
    id: 'us-sanfrancisco',
    name: 'सैन फ्रांसिस्को (San Francisco)',
    nameHi: 'सैन फ्रांसिस्को',
    nameEn: 'San Francisco',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'कैलिफ़ोर्निया (CA)',
    regionEn: 'California',
    latitude: 37.7749,
    longitude: -122.4194,
    timezone: 'America/Los_Angeles',
    timezoneHours: -8,
    type: 'metro',
  },
  {
    id: 'us-fremont',
    name: 'फ्रीमोंट (Fremont)',
    nameHi: 'फ्रीमोंट',
    nameEn: 'Fremont',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'कैलिफ़ोर्निया (CA)',
    regionEn: 'California',
    latitude: 37.5485,
    longitude: -121.9886,
    timezone: 'America/Los_Angeles',
    timezoneHours: -8,
    type: 'major',
  },
  {
    id: 'us-sunnyvale',
    name: 'सनीवेल (Sunnyvale)',
    nameHi: 'सनीवेल',
    nameEn: 'Sunnyvale',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'कैलिफ़ोर्निया (CA)',
    regionEn: 'California',
    latitude: 37.3688,
    longitude: -122.0363,
    timezone: 'America/Los_Angeles',
    timezoneHours: -8,
    type: 'major',
  },
  {
    id: 'us-losangeles',
    name: 'लॉस एंजिल्स (Los Angeles)',
    nameHi: 'लॉस एंजिल्स',
    nameEn: 'Los Angeles',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'कैलिफ़ोर्निया (CA)',
    regionEn: 'California',
    latitude: 34.0522,
    longitude: -118.2437,
    timezone: 'America/Los_Angeles',
    timezoneHours: -8,
    type: 'metro',
  },
  {
    id: 'us-irvine',
    name: 'इरविन (Irvine)',
    nameHi: 'इरविन',
    nameEn: 'Irvine',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'कैलिफ़ोर्निया (CA)',
    regionEn: 'California',
    latitude: 33.6846,
    longitude: -117.8265,
    timezone: 'America/Los_Angeles',
    timezoneHours: -8,
    type: 'major',
  },
  {
    id: 'us-sandiego',
    name: 'सैन डिएगो (San Diego)',
    nameHi: 'सैन डिएगो',
    nameEn: 'San Diego',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'कैलिफ़ोर्निया (CA)',
    regionEn: 'California',
    latitude: 32.7157,
    longitude: -117.1611,
    timezone: 'America/Los_Angeles',
    timezoneHours: -8,
    type: 'major',
  },
  {
    id: 'us-chicago',
    name: 'शिकागो (Chicago)',
    nameHi: 'शिकागो',
    nameEn: 'Chicago',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'इलिनोइस (IL)',
    regionEn: 'Illinois',
    latitude: 41.8781,
    longitude: -87.6298,
    timezone: 'America/Chicago',
    timezoneHours: -6,
    type: 'metro',
  },
  {
    id: 'us-naperville',
    name: 'नेपरविले (Naperville)',
    nameHi: 'नेपरविले',
    nameEn: 'Naperville',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'इलिनोइस (IL)',
    regionEn: 'Illinois',
    latitude: 41.7508,
    longitude: -88.1535,
    timezone: 'America/Chicago',
    timezoneHours: -6,
    type: 'major',
  },
  {
    id: 'us-dallas',
    name: 'डलास (Dallas)',
    nameHi: 'डलास',
    nameEn: 'Dallas',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'टेक्सास (TX)',
    regionEn: 'Texas',
    latitude: 32.7767,
    longitude: -96.797,
    timezone: 'America/Chicago',
    timezoneHours: -6,
    type: 'metro',
  },
  {
    id: 'us-houston',
    name: 'ह्यूस्टन (Houston)',
    nameHi: 'ह्यूस्टन',
    nameEn: 'Houston',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'टेक्सास (TX)',
    regionEn: 'Texas',
    latitude: 29.7604,
    longitude: -95.3698,
    timezone: 'America/Chicago',
    timezoneHours: -6,
    type: 'metro',
  },
  {
    id: 'us-austin',
    name: 'ऑस्टिन (Austin)',
    nameHi: 'ऑस्टिन',
    nameEn: 'Austin',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'टेक्सास (TX)',
    regionEn: 'Texas',
    latitude: 30.2672,
    longitude: -97.7431,
    timezone: 'America/Chicago',
    timezoneHours: -6,
    type: 'major',
  },
  {
    id: 'us-plano',
    name: 'प्लानो (Plano)',
    nameHi: 'प्लानो',
    nameEn: 'Plano',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'टेक्सास (TX)',
    regionEn: 'Texas',
    latitude: 33.0198,
    longitude: -96.6989,
    timezone: 'America/Chicago',
    timezoneHours: -6,
    type: 'major',
  },
  {
    id: 'us-frisco',
    name: 'फ्रिस्को (Frisco)',
    nameHi: 'फ्रिस्को',
    nameEn: 'Frisco',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'टेक्सास (TX)',
    regionEn: 'Texas',
    latitude: 33.1507,
    longitude: -96.8236,
    timezone: 'America/Chicago',
    timezoneHours: -6,
    type: 'major',
  },
  {
    id: 'us-seattle',
    name: 'सिएटल (Seattle)',
    nameHi: 'सिएटल',
    nameEn: 'Seattle',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'वाशिंगटन (WA)',
    regionEn: 'Washington',
    latitude: 47.6062,
    longitude: -122.3321,
    timezone: 'America/Los_Angeles',
    timezoneHours: -8,
    type: 'metro',
  },
  {
    id: 'us-bellevue',
    name: 'बेलेव्यू (Bellevue)',
    nameHi: 'बेलेव्यू',
    nameEn: 'Bellevue',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'वाशिंगटन (WA)',
    regionEn: 'Washington',
    latitude: 47.6101,
    longitude: -122.2015,
    timezone: 'America/Los_Angeles',
    timezoneHours: -8,
    type: 'major',
  },
  {
    id: 'us-atlanta',
    name: 'अटलांटा (Atlanta)',
    nameHi: 'अटलांटा',
    nameEn: 'Atlanta',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'जॉर्जिया (GA)',
    regionEn: 'Georgia',
    latitude: 33.749,
    longitude: -84.388,
    timezone: 'America/New_York',
    timezoneHours: -5,
    type: 'metro',
  },
  {
    id: 'us-alpharetta',
    name: 'अल्फ़ारेटा (Alpharetta)',
    nameHi: 'अल्फ़ारेटा',
    nameEn: 'Alpharetta',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'जॉर्जिया (GA)',
    regionEn: 'Georgia',
    latitude: 34.0754,
    longitude: -84.2941,
    timezone: 'America/New_York',
    timezoneHours: -5,
    type: 'major',
  },
  {
    id: 'us-washingtondc',
    name: 'वाशिंगटन डी.सी. (Washington D.C.)',
    nameHi: 'वाशिंगटन डी.सी.',
    nameEn: 'Washington D.C.',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'डिस्ट्रिक्ट ऑफ कोलंबिया (DC)',
    regionEn: 'District of Columbia',
    latitude: 38.9072,
    longitude: -77.0369,
    timezone: 'America/New_York',
    timezoneHours: -5,
    type: 'capital',
  },
  {
    id: 'us-boston',
    name: 'बोस्टन (Boston)',
    nameHi: 'बोस्टन',
    nameEn: 'Boston',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'मैसाचुसेट्स (MA)',
    regionEn: 'Massachusetts',
    latitude: 42.3601,
    longitude: -71.0589,
    timezone: 'America/New_York',
    timezoneHours: -5,
    type: 'major',
  },
  {
    id: 'us-tampa',
    name: 'टैम्पा (Tampa)',
    nameHi: 'टैम्पा',
    nameEn: 'Tampa',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'फ्लोरिडा (FL)',
    regionEn: 'Florida',
    latitude: 27.9506,
    longitude: -82.4572,
    timezone: 'America/New_York',
    timezoneHours: -5,
    type: 'major',
  },
  {
    id: 'us-orlando',
    name: 'ऑरलैंडो (Orlando)',
    nameHi: 'ऑरलैंडो',
    nameEn: 'Orlando',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'फ्लोरिडा (FL)',
    regionEn: 'Florida',
    latitude: 28.5383,
    longitude: -81.3792,
    timezone: 'America/New_York',
    timezoneHours: -5,
    type: 'major',
  },
  {
    id: 'us-phoenix',
    name: 'फीनिक्स (Phoenix)',
    nameHi: 'फीनिक्स',
    nameEn: 'Phoenix',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'एरिज़ोना (AZ)',
    regionEn: 'Arizona',
    latitude: 33.4484,
    longitude: -112.074,
    timezone: 'America/Phoenix',
    timezoneHours: -7,
    type: 'major',
  },
  {
    id: 'us-detroit',
    name: 'डेट्रॉइट (Detroit)',
    nameHi: 'डेट्रॉइट',
    nameEn: 'Detroit',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'मिशिगन (MI)',
    regionEn: 'Michigan',
    latitude: 42.3314,
    longitude: -83.0458,
    timezone: 'America/Detroit',
    timezoneHours: -5,
    type: 'major',
  },
  {
    id: 'us-philadelphia',
    name: 'फिलाडेल्फिया (Philadelphia)',
    nameHi: 'फिलाडेल्फिया',
    nameEn: 'Philadelphia',
    country: 'USA',
    countryEn: 'United States',
    countryCode: 'US',
    flag: '🇺🇸',
    region: 'पेंसिल्वेनिया (PA)',
    regionEn: 'Pennsylvania',
    latitude: 39.9526,
    longitude: -75.1652,
    timezone: 'America/New_York',
    timezoneHours: -5,
    type: 'major',
  },

  // ==========================================
  // यूनाइटेड किंगडम (UNITED KINGDOM - UK)
  // ==========================================
  {
    id: 'gb-london',
    name: 'लंदन (London)',
    nameHi: 'लंदन',
    nameEn: 'London',
    country: 'UK',
    countryEn: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    region: 'ग्रेटर लंदन',
    regionEn: 'Greater London',
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: 'Europe/London',
    timezoneHours: 0,
    type: 'capital',
  },
  {
    id: 'gb-wembley',
    name: 'वेम्बली (Wembley)',
    nameHi: 'वेम्बली',
    nameEn: 'Wembley',
    country: 'UK',
    countryEn: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    region: 'लंदन',
    regionEn: 'London',
    latitude: 51.5505,
    longitude: -0.3048,
    timezone: 'Europe/London',
    timezoneHours: 0,
    type: 'major',
  },
  {
    id: 'gb-leicester',
    name: 'लीसेस्टर (Leicester)',
    nameHi: 'लीसेस्टर',
    nameEn: 'Leicester',
    country: 'UK',
    countryEn: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    region: 'ईस्ट मिडलैंड्स',
    regionEn: 'East Midlands',
    latitude: 52.6369,
    longitude: -1.1398,
    timezone: 'Europe/London',
    timezoneHours: 0,
    type: 'major',
  },
  {
    id: 'gb-birmingham',
    name: 'बर्मिंघम (Birmingham)',
    nameHi: 'बर्मिंघम',
    nameEn: 'Birmingham',
    country: 'UK',
    countryEn: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    region: 'वेस्ट मिडलैंड्स',
    regionEn: 'West Midlands',
    latitude: 52.4862,
    longitude: -1.8904,
    timezone: 'Europe/London',
    timezoneHours: 0,
    type: 'major',
  },
  {
    id: 'gb-manchester',
    name: 'मैनचेस्टर (Manchester)',
    nameHi: 'मैनचेस्टर',
    nameEn: 'Manchester',
    country: 'UK',
    countryEn: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    region: 'ग्रेटर मैनचेस्टर',
    regionEn: 'Greater Manchester',
    latitude: 53.4808,
    longitude: -2.2426,
    timezone: 'Europe/London',
    timezoneHours: 0,
    type: 'major',
  },
  {
    id: 'gb-glasgow',
    name: 'ग्लासगो (Glasgow)',
    nameHi: 'ग्लासगो',
    nameEn: 'Glasgow',
    country: 'UK',
    countryEn: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    region: 'स्कॉटलैंड',
    regionEn: 'Scotland',
    latitude: 55.8642,
    longitude: -4.2518,
    timezone: 'Europe/London',
    timezoneHours: 0,
    type: 'major',
  },
  {
    id: 'gb-edinburgh',
    name: 'एडिनबर्ग (Edinburgh)',
    nameHi: 'एडिनबर्ग',
    nameEn: 'Edinburgh',
    country: 'UK',
    countryEn: 'United Kingdom',
    countryCode: 'GB',
    flag: '🇬🇧',
    region: 'स्कॉटलैंड',
    regionEn: 'Scotland',
    latitude: 55.9533,
    longitude: -3.1883,
    timezone: 'Europe/London',
    timezoneHours: 0,
    type: 'major',
  },

  // ==========================================
  // कनाडा (CANADA)
  // ==========================================
  {
    id: 'ca-toronto',
    name: 'टोरंटो (Toronto)',
    nameHi: 'टोरंटो',
    nameEn: 'Toronto',
    country: 'कनाडा',
    countryEn: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    region: 'ओंटारियो (ON)',
    regionEn: 'Ontario',
    latitude: 43.6532,
    longitude: -79.3832,
    timezone: 'America/Toronto',
    timezoneHours: -5,
    type: 'metro',
  },
  {
    id: 'ca-brampton',
    name: 'ब्रैम्पटन (Brampton)',
    nameHi: 'ब्रैम्पटन',
    nameEn: 'Brampton',
    country: 'कनाडा',
    countryEn: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    region: 'ओंटारियो (ON)',
    regionEn: 'Ontario',
    latitude: 43.7315,
    longitude: -79.7624,
    timezone: 'America/Toronto',
    timezoneHours: -5,
    type: 'major',
  },
  {
    id: 'ca-mississauga',
    name: 'मिसिसागा (Mississauga)',
    nameHi: 'मिसिसागा',
    nameEn: 'Mississauga',
    country: 'कनाडा',
    countryEn: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    region: 'ओंटारियो (ON)',
    regionEn: 'Ontario',
    latitude: 43.589,
    longitude: -79.6441,
    timezone: 'America/Toronto',
    timezoneHours: -5,
    type: 'major',
  },
  {
    id: 'ca-vancouver',
    name: 'वैंकूवर (Vancouver)',
    nameHi: 'वैंकूवर',
    nameEn: 'Vancouver',
    country: 'कनाडा',
    countryEn: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    region: 'ब्रिटिश कोलंबिया (BC)',
    regionEn: 'British Columbia',
    latitude: 49.2827,
    longitude: -123.1207,
    timezone: 'America/Vancouver',
    timezoneHours: -8,
    type: 'metro',
  },
  {
    id: 'ca-surrey',
    name: 'सरे (Surrey)',
    nameHi: 'सरे',
    nameEn: 'Surrey',
    country: 'कनाडा',
    countryEn: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    region: 'ब्रिटिश कोलंबिया (BC)',
    regionEn: 'British Columbia',
    latitude: 49.1913,
    longitude: -122.849,
    timezone: 'America/Vancouver',
    timezoneHours: -8,
    type: 'major',
  },
  {
    id: 'ca-calgary',
    name: 'कैलगरी (Calgary)',
    nameHi: 'कैलगरी',
    nameEn: 'Calgary',
    country: 'कनाडा',
    countryEn: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    region: 'अल्बर्टा (AB)',
    regionEn: 'Alberta',
    latitude: 51.0447,
    longitude: -114.0719,
    timezone: 'America/Edmonton',
    timezoneHours: -7,
    type: 'major',
  },
  {
    id: 'ca-edmonton',
    name: 'एडमोंटन (Edmonton)',
    nameHi: 'एडमोंटन',
    nameEn: 'Edmonton',
    country: 'कनाडा',
    countryEn: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    region: 'अल्बर्टा (AB)',
    regionEn: 'Alberta',
    latitude: 53.5461,
    longitude: -113.4938,
    timezone: 'America/Edmonton',
    timezoneHours: -7,
    type: 'major',
  },
  {
    id: 'ca-montreal',
    name: 'मॉन्ट्रियल (Montreal)',
    nameHi: 'मॉन्ट्रियल',
    nameEn: 'Montreal',
    country: 'कनाडा',
    countryEn: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    region: 'क्यूबेक (QC)',
    regionEn: 'Quebec',
    latitude: 45.5017,
    longitude: -73.5673,
    timezone: 'America/Montreal',
    timezoneHours: -5,
    type: 'major',
  },

  // ========================================================
  // संयुक्त अरब अमीरात एवं खाड़ी देश (UAE & GULF COUNTRIES)
  // ========================================================
  {
    id: 'ae-dubai',
    name: 'दुबई (Dubai)',
    nameHi: 'दुबई',
    nameEn: 'Dubai',
    country: 'UAE',
    countryEn: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    region: 'दुबई अमीरात',
    regionEn: 'Dubai',
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: 'Asia/Dubai',
    timezoneHours: 4,
    type: 'metro',
  },
  {
    id: 'ae-abudhabi',
    name: 'अबू धाबी (Abu Dhabi)',
    nameHi: 'अबू धाबी',
    nameEn: 'Abu Dhabi',
    country: 'UAE',
    countryEn: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    region: 'अबू धाबी',
    regionEn: 'Abu Dhabi',
    latitude: 24.4539,
    longitude: 54.3773,
    timezone: 'Asia/Dubai',
    timezoneHours: 4,
    type: 'capital',
  },
  {
    id: 'ae-sharjah',
    name: 'शारजाह (Sharjah)',
    nameHi: 'शारजाह',
    nameEn: 'Sharjah',
    country: 'UAE',
    countryEn: 'United Arab Emirates',
    countryCode: 'AE',
    flag: '🇦🇪',
    region: 'शारजाह',
    regionEn: 'Sharjah',
    latitude: 25.3463,
    longitude: 55.4209,
    timezone: 'Asia/Dubai',
    timezoneHours: 4,
    type: 'major',
  },
  {
    id: 'qa-doha',
    name: 'दोहा (Doha)',
    nameHi: 'दोहा',
    nameEn: 'Doha',
    country: 'कतर',
    countryEn: 'Qatar',
    countryCode: 'QA',
    flag: '🇶🇦',
    region: 'अद-दौहा',
    regionEn: 'Ad Dawhah',
    latitude: 25.2854,
    longitude: 51.531,
    timezone: 'Asia/Qatar',
    timezoneHours: 3,
    type: 'capital',
  },
  {
    id: 'om-muscat',
    name: 'मस्कट (Muscat)',
    nameHi: 'मस्कट',
    nameEn: 'Muscat',
    country: 'ओमान',
    countryEn: 'Oman',
    countryCode: 'OM',
    flag: '🇴🇲',
    region: 'मस्कट',
    regionEn: 'Muscat',
    latitude: 23.588,
    longitude: 58.3829,
    timezone: 'Asia/Muscat',
    timezoneHours: 4,
    type: 'capital',
  },
  {
    id: 'kw-kuwaitcity',
    name: 'कुवैत सिटी (Kuwait City)',
    nameHi: 'कुवैत सिटी',
    nameEn: 'Kuwait City',
    country: 'कुवैत',
    countryEn: 'Kuwait',
    countryCode: 'KW',
    flag: '🇰🇼',
    region: 'अल आसिमह',
    regionEn: 'Al Asimah',
    latitude: 29.3759,
    longitude: 47.9774,
    timezone: 'Asia/Kuwait',
    timezoneHours: 3,
    type: 'capital',
  },
  {
    id: 'bh-manama',
    name: 'मनामा (Manama)',
    nameHi: 'मनामा',
    nameEn: 'Manama',
    country: 'बहरीन',
    countryEn: 'Bahrain',
    countryCode: 'BH',
    flag: '🇧🇭',
    region: 'राजधानी प्रांत',
    regionEn: 'Capital Governorate',
    latitude: 26.2285,
    longitude: 50.586,
    timezone: 'Asia/Bahrain',
    timezoneHours: 3,
    type: 'capital',
  },
  {
    id: 'sa-riyadh',
    name: 'रियाद (Riyadh)',
    nameHi: 'रियाद',
    nameEn: 'Riyadh',
    country: 'सऊदी अरब',
    countryEn: 'Saudi Arabia',
    countryCode: 'SA',
    flag: '🇸🇦',
    region: 'रियाद प्रांत',
    regionEn: 'Riyadh Province',
    latitude: 24.7136,
    longitude: 46.6753,
    timezone: 'Asia/Riyadh',
    timezoneHours: 3,
    type: 'capital',
  },
  {
    id: 'sa-jeddah',
    name: 'जेद्दाह (Jeddah)',
    nameHi: 'जेद्दाह',
    nameEn: 'Jeddah',
    country: 'सऊदी अरब',
    countryEn: 'Saudi Arabia',
    countryCode: 'SA',
    flag: '🇸🇦',
    region: 'मक्का प्रांत',
    regionEn: 'Makkah Province',
    latitude: 21.4858,
    longitude: 39.1925,
    timezone: 'Asia/Riyadh',
    timezoneHours: 3,
    type: 'major',
  },

  // ==========================================
  // ऑस्ट्रेलिया एवं न्यूज़ीलैंड (AUSTRALASIA)
  // ==========================================
  {
    id: 'au-sydney',
    name: 'सिडनी (Sydney)',
    nameHi: 'सिडनी',
    nameEn: 'Sydney',
    country: 'ऑस्ट्रेलिया',
    countryEn: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    region: 'न्यू साउथ वेल्स (NSW)',
    regionEn: 'New South Wales',
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: 'Australia/Sydney',
    timezoneHours: 10,
    type: 'metro',
  },
  {
    id: 'au-melbourne',
    name: 'मेलबर्न (Melbourne)',
    nameHi: 'मेलबर्न',
    nameEn: 'Melbourne',
    country: 'ऑस्ट्रेलिया',
    countryEn: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    region: 'विक्टोरिया (VIC)',
    regionEn: 'Victoria',
    latitude: -37.8136,
    longitude: 144.9631,
    timezone: 'Australia/Melbourne',
    timezoneHours: 10,
    type: 'metro',
  },
  {
    id: 'au-brisbane',
    name: 'ब्रिस्बेन (Brisbane)',
    nameHi: 'ब्रिस्बेन',
    nameEn: 'Brisbane',
    country: 'ऑस्ट्रेलिया',
    countryEn: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    region: 'क्वींसलैंड (QLD)',
    regionEn: 'Queensland',
    latitude: -27.4698,
    longitude: 153.0251,
    timezone: 'Australia/Brisbane',
    timezoneHours: 10,
    type: 'major',
  },
  {
    id: 'au-perth',
    name: 'पर्थ (Perth)',
    nameHi: 'पर्थ',
    nameEn: 'Perth',
    country: 'ऑस्ट्रेलिया',
    countryEn: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    region: 'वेस्टर्न ऑस्ट्रेलिया (WA)',
    regionEn: 'Western Australia',
    latitude: -31.9505,
    longitude: 115.8605,
    timezone: 'Australia/Perth',
    timezoneHours: 8,
    type: 'major',
  },
  {
    id: 'au-adelaide',
    name: 'एडिलेड (Adelaide)',
    nameHi: 'एडिलेड',
    nameEn: 'Adelaide',
    country: 'ऑस्ट्रेलिया',
    countryEn: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    region: 'साउथ ऑस्ट्रेलिया (SA)',
    regionEn: 'South Australia',
    latitude: -34.9285,
    longitude: 138.6007,
    timezone: 'Australia/Adelaide',
    timezoneHours: 9.5,
    type: 'major',
  },
  {
    id: 'au-canberra',
    name: 'कैनबरा (Canberra)',
    nameHi: 'कैनबरा',
    nameEn: 'Canberra',
    country: 'ऑस्ट्रेलिया',
    countryEn: 'Australia',
    countryCode: 'AU',
    flag: '🇦🇺',
    region: 'कैपिटल टेरिटरी (ACT)',
    regionEn: 'Australian Capital Territory',
    latitude: -35.2809,
    longitude: 149.13,
    timezone: 'Australia/Sydney',
    timezoneHours: 10,
    type: 'capital',
  },
  {
    id: 'nz-auckland',
    name: 'ऑकलैंड (Auckland)',
    nameHi: 'ऑकलैंड',
    nameEn: 'Auckland',
    country: 'न्यूजीलैंड',
    countryEn: 'New Zealand',
    countryCode: 'NZ',
    flag: '🇳🇿',
    region: 'ऑकलैंड क्षेत्र',
    regionEn: 'Auckland Region',
    latitude: -36.8485,
    longitude: 174.7633,
    timezone: 'Pacific/Auckland',
    timezoneHours: 12,
    type: 'metro',
  },
  {
    id: 'nz-wellington',
    name: 'वेलिंगटन (Wellington)',
    nameHi: 'वेलिंगटन',
    nameEn: 'Wellington',
    country: 'न्यूजीलैंड',
    countryEn: 'New Zealand',
    countryCode: 'NZ',
    flag: '🇳🇿',
    region: 'वेलिंगटन क्षेत्र',
    regionEn: 'Wellington Region',
    latitude: -41.2865,
    longitude: 174.7762,
    timezone: 'Pacific/Auckland',
    timezoneHours: 12,
    type: 'capital',
  },

  // ==========================================
  // नेपाल (NEPAL)
  // ==========================================
  {
    id: 'np-kathmandu',
    name: 'काठमांडू / पशुपतिनाथ (Kathmandu)',
    nameHi: 'काठमांडू / पशुपतिनाथ',
    nameEn: 'Kathmandu / Pashupatinath',
    country: 'नेपाल',
    countryEn: 'Nepal',
    countryCode: 'NP',
    flag: '🇳🇵',
    region: 'बागमती प्रदेश',
    regionEn: 'Bagmati Province',
    latitude: 27.7172,
    longitude: 85.324,
    timezone: 'Asia/Kathmandu',
    timezoneHours: 5.75,
    type: 'pilgrimage',
  },
  {
    id: 'np-janakpur',
    name: 'जनकपुर धाम (Janakpur Dham)',
    nameHi: 'जनकपुर धाम',
    nameEn: 'Janakpur Dham',
    country: 'नेपाल',
    countryEn: 'Nepal',
    countryCode: 'NP',
    flag: '🇳🇵',
    region: 'मधेश प्रदेश',
    regionEn: 'Madhesh Province',
    latitude: 26.7288,
    longitude: 85.9244,
    timezone: 'Asia/Kathmandu',
    timezoneHours: 5.75,
    type: 'pilgrimage',
  },
  {
    id: 'np-pokhara',
    name: 'पोखरा (Pokhara)',
    nameHi: 'पोखरा',
    nameEn: 'Pokhara',
    country: 'नेपाल',
    countryEn: 'Nepal',
    countryCode: 'NP',
    flag: '🇳🇵',
    region: 'गंडकी प्रदेश',
    regionEn: 'Gandaki Province',
    latitude: 28.2096,
    longitude: 83.9856,
    timezone: 'Asia/Kathmandu',
    timezoneHours: 5.75,
    type: 'major',
  },
  {
    id: 'np-lumbini',
    name: 'लुम्बिनी (Lumbini)',
    nameHi: 'लुम्बिनी',
    nameEn: 'Lumbini',
    country: 'नेपाल',
    countryEn: 'Nepal',
    countryCode: 'NP',
    flag: '🇳🇵',
    region: 'लुम्बिनी प्रदेश',
    regionEn: 'Lumbini Province',
    latitude: 27.4839,
    longitude: 83.2759,
    timezone: 'Asia/Kathmandu',
    timezoneHours: 5.75,
    type: 'pilgrimage',
  },
  {
    id: 'np-biratnagar',
    name: 'विराटनगर (Biratnagar)',
    nameHi: 'विराटनगर',
    nameEn: 'Biratnagar',
    country: 'नेपाल',
    countryEn: 'Nepal',
    countryCode: 'NP',
    flag: '🇳🇵',
    region: 'कोशी प्रदेश',
    regionEn: 'Koshi Province',
    latitude: 26.4525,
    longitude: 87.2718,
    timezone: 'Asia/Kathmandu',
    timezoneHours: 5.75,
    type: 'major',
  },

  // ==========================================
  // मॉरीशस, फिजी एवं दक्षिण अफ्रीका
  // ==========================================
  {
    id: 'mu-portlouis',
    name: 'पोर्ट लुइस (Port Louis)',
    nameHi: 'पोर्ट लुइस',
    nameEn: 'Port Louis',
    country: 'मॉरीशस',
    countryEn: 'Mauritius',
    countryCode: 'MU',
    flag: '🇲🇺',
    region: 'पोर्ट लुइस जिला',
    regionEn: 'Port Louis District',
    latitude: -20.1609,
    longitude: 57.5012,
    timezone: 'Indian/Mauritius',
    timezoneHours: 4,
    type: 'capital',
  },
  {
    id: 'mu-curepipe',
    name: 'क्यूरपाइप (Curepipe)',
    nameHi: 'क्यूरपाइप',
    nameEn: 'Curepipe',
    country: 'मॉरीशस',
    countryEn: 'Mauritius',
    countryCode: 'MU',
    flag: '🇲🇺',
    region: 'प्लाइन्स विल्हेम्स',
    regionEn: 'Plaines Wilhems',
    latitude: -20.3167,
    longitude: 57.5167,
    timezone: 'Indian/Mauritius',
    timezoneHours: 4,
    type: 'major',
  },
  {
    id: 'fj-suva',
    name: 'सुवा (Suva)',
    nameHi: 'सुवा',
    nameEn: 'Suva',
    country: 'फिजी',
    countryEn: 'Fiji',
    countryCode: 'FJ',
    flag: '🇫🇯',
    region: 'सेंट्रल डिवीजन',
    regionEn: 'Central Division',
    latitude: -18.1416,
    longitude: 178.4419,
    timezone: 'Pacific/Fiji',
    timezoneHours: 12,
    type: 'capital',
  },
  {
    id: 'fj-nadi',
    name: 'नादी (Nadi)',
    nameHi: 'नादी',
    nameEn: 'Nadi',
    country: 'फिजी',
    countryEn: 'Fiji',
    countryCode: 'FJ',
    flag: '🇫🇯',
    region: 'वेस्टर्न डिवीजन',
    regionEn: 'Western Division',
    latitude: -17.7999,
    longitude: 177.4173,
    timezone: 'Pacific/Fiji',
    timezoneHours: 12,
    type: 'major',
  },
  {
    id: 'za-johannesburg',
    name: 'जोहान्सबर्ग (Johannesburg)',
    nameHi: 'जोहान्सबर्ग',
    nameEn: 'Johannesburg',
    country: 'दक्षिण अफ्रीका',
    countryEn: 'South Africa',
    countryCode: 'ZA',
    flag: '🇿🇦',
    region: 'गौतेंग',
    regionEn: 'Gauteng',
    latitude: -26.2041,
    longitude: 28.0473,
    timezone: 'Africa/Johannesburg',
    timezoneHours: 2,
    type: 'metro',
  },
  {
    id: 'za-durban',
    name: 'डरबन (Durban)',
    nameHi: 'डरबन',
    nameEn: 'Durban',
    country: 'दक्षिण अफ्रीका',
    countryEn: 'South Africa',
    countryCode: 'ZA',
    flag: '🇿🇦',
    region: 'क्वाजुलू-नताल',
    regionEn: 'KwaZulu-Natal',
    latitude: -29.8587,
    longitude: 31.0218,
    timezone: 'Africa/Johannesburg',
    timezoneHours: 2,
    type: 'major',
  },

  // ==========================================
  // दक्षिण-पूर्व एशिया (SOUTHEAST ASIA)
  // ==========================================
  {
    id: 'sg-singapore',
    name: 'सिंगापुर सिटी (Singapore)',
    nameHi: 'सिंगापुर सिटी',
    nameEn: 'Singapore',
    country: 'सिंगापुर',
    countryEn: 'Singapore',
    countryCode: 'SG',
    flag: '🇸🇬',
    region: 'सिंगापुर',
    regionEn: 'Singapore',
    latitude: 1.3521,
    longitude: 103.8198,
    timezone: 'Asia/Singapore',
    timezoneHours: 8,
    type: 'capital',
  },
  {
    id: 'my-kualalumpur',
    name: 'कुआलालंपुर / बाटू केव्स (Kuala Lumpur)',
    nameHi: 'कुआलालंपुर / बाटू केव्स',
    nameEn: 'Kuala Lumpur / Batu Caves',
    country: 'मलेशिया',
    countryEn: 'Malaysia',
    countryCode: 'MY',
    flag: '🇲🇾',
    region: 'संघीय क्षेत्र',
    regionEn: 'Federal Territory',
    latitude: 3.139,
    longitude: 101.6869,
    timezone: 'Asia/Kuala_Lumpur',
    timezoneHours: 8,
    type: 'capital',
  },
  {
    id: 'my-penang',
    name: 'पेनांग (Penang)',
    nameHi: 'पेनांग',
    nameEn: 'Penang',
    country: 'मलेशिया',
    countryEn: 'Malaysia',
    countryCode: 'MY',
    flag: '🇲🇾',
    region: 'पेनांग',
    regionEn: 'Penang',
    latitude: 5.4141,
    longitude: 100.3288,
    timezone: 'Asia/Kuala_Lumpur',
    timezoneHours: 8,
    type: 'major',
  },
  {
    id: 'id-bali',
    name: 'बाली / देनपसार (Denpasar / Bali)',
    nameHi: 'बाली / देनपसार',
    nameEn: 'Denpasar / Bali',
    country: 'इंडोनेशिया',
    countryEn: 'Indonesia',
    countryCode: 'ID',
    flag: '🇮🇩',
    region: 'बाली द्वीप',
    regionEn: 'Bali',
    latitude: -8.6705,
    longitude: 115.2126,
    timezone: 'Asia/Makassar',
    timezoneHours: 8,
    type: 'pilgrimage',
  },
  {
    id: 'id-jakarta',
    name: 'जकार्ता (Jakarta)',
    nameHi: 'जकार्ता',
    nameEn: 'Jakarta',
    country: 'इंडोनेशिया',
    countryEn: 'Indonesia',
    countryCode: 'ID',
    flag: '🇮🇩',
    region: 'जावा',
    regionEn: 'Java',
    latitude: -6.2088,
    longitude: 106.8456,
    timezone: 'Asia/Jakarta',
    timezoneHours: 7,
    type: 'capital',
  },
  {
    id: 'th-bangkok',
    name: 'बैंकॉक (Bangkok)',
    nameHi: 'बैंकॉक',
    nameEn: 'Bangkok',
    country: 'थाईलैंड',
    countryEn: 'Thailand',
    countryCode: 'TH',
    flag: '🇹🇭',
    region: 'सेंट्रल थाईलैंड',
    regionEn: 'Central Thailand',
    latitude: 13.7563,
    longitude: 100.5018,
    timezone: 'Asia/Bangkok',
    timezoneHours: 7,
    type: 'capital',
  },
  {
    id: 'lk-colombo',
    name: 'कोलंबो (Colombo)',
    nameHi: 'कोलंबो',
    nameEn: 'Colombo',
    country: 'श्रीलंका',
    countryEn: 'Sri Lanka',
    countryCode: 'LK',
    flag: '🇱🇰',
    region: 'पश्चिमी प्रांत',
    regionEn: 'Western Province',
    latitude: 6.9271,
    longitude: 79.8612,
    timezone: 'Asia/Colombo',
    timezoneHours: 5.5,
    type: 'capital',
  },
  {
    id: 'jp-tokyo',
    name: 'टोक्यो (Tokyo)',
    nameHi: 'टोक्यो',
    nameEn: 'Tokyo',
    country: 'जापान',
    countryEn: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    region: 'कांटो',
    regionEn: 'Kanto',
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: 'Asia/Tokyo',
    timezoneHours: 9,
    type: 'capital',
  },

  // ==========================================
  // यूरोप (EUROPE)
  // ==========================================
  {
    id: 'de-berlin',
    name: 'बर्लिन (Berlin)',
    nameHi: 'बर्लिन',
    nameEn: 'Berlin',
    country: 'जर्मनी',
    countryEn: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    region: 'बर्लिन राज्य',
    regionEn: 'Berlin',
    latitude: 52.52,
    longitude: 13.405,
    timezone: 'Europe/Berlin',
    timezoneHours: 1,
    type: 'capital',
  },
  {
    id: 'de-frankfurt',
    name: 'फ्रैंकफर्ट (Frankfurt)',
    nameHi: 'फ्रैंकफर्ट',
    nameEn: 'Frankfurt',
    country: 'जर्मनी',
    countryEn: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    region: 'हेस्से',
    regionEn: 'Hesse',
    latitude: 50.1109,
    longitude: 8.6821,
    timezone: 'Europe/Berlin',
    timezoneHours: 1,
    type: 'major',
  },
  {
    id: 'de-munich',
    name: 'म्यूनिख (Munich)',
    nameHi: 'म्यूनिख',
    nameEn: 'Munich',
    country: 'जर्मनी',
    countryEn: 'Germany',
    countryCode: 'DE',
    flag: '🇩🇪',
    region: 'बवेरिया',
    regionEn: 'Bavaria',
    latitude: 48.1351,
    longitude: 11.582,
    timezone: 'Europe/Berlin',
    timezoneHours: 1,
    type: 'major',
  },
  {
    id: 'fr-paris',
    name: 'पेरिस (Paris)',
    nameHi: 'पेरिस',
    nameEn: 'Paris',
    country: 'फ्रांस',
    countryEn: 'France',
    countryCode: 'FR',
    flag: '🇫🇷',
    region: 'इले-द-फ्रांस',
    regionEn: 'Ile-de-France',
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: 'Europe/Paris',
    timezoneHours: 1,
    type: 'capital',
  },
  {
    id: 'nl-amsterdam',
    name: 'एम्स्टर्डम (Amsterdam)',
    nameHi: 'एम्स्टर्डम',
    nameEn: 'Amsterdam',
    country: 'नीदरलैंड',
    countryEn: 'Netherlands',
    countryCode: 'NL',
    flag: '🇳🇱',
    region: 'उत्तरी हॉलैंड',
    regionEn: 'North Holland',
    latitude: 52.3676,
    longitude: 4.9041,
    timezone: 'Europe/Amsterdam',
    timezoneHours: 1,
    type: 'capital',
  },
  {
    id: 'ch-zurich',
    name: 'ज्यूरिख (Zurich)',
    nameHi: 'ज्यूरिख',
    nameEn: 'Zurich',
    country: 'स्विट्जरलैंड',
    countryEn: 'Switzerland',
    countryCode: 'CH',
    flag: '🇨🇭',
    region: 'ज्यूरिख केंटन',
    regionEn: 'Zurich',
    latitude: 47.3769,
    longitude: 8.5417,
    timezone: 'Europe/Zurich',
    timezoneHours: 1,
    type: 'major',
  },
  {
    id: 'ie-dublin',
    name: 'डबलिन (Dublin)',
    nameHi: 'डबलिन',
    nameEn: 'Dublin',
    country: 'आयरलैंड',
    countryEn: 'Ireland',
    countryCode: 'IE',
    flag: '🇮🇪',
    region: 'लेनस्टर',
    regionEn: 'Leinster',
    latitude: 53.3498,
    longitude: -6.2603,
    timezone: 'Europe/Dublin',
    timezoneHours: 0,
    type: 'capital',
  },
  {
    id: 'it-rome',
    name: 'रोम (Rome)',
    nameHi: 'रोम',
    nameEn: 'Rome',
    country: 'इटली',
    countryEn: 'Italy',
    countryCode: 'IT',
    flag: '🇮🇹',
    region: 'लाज़ियो',
    regionEn: 'Lazio',
    latitude: 41.9028,
    longitude: 12.4964,
    timezone: 'Europe/Rome',
    timezoneHours: 1,
    type: 'capital',
  },

  // ==========================================
  // कैरेबियन एवं अमेरिका (CARIBBEAN & AMERICAS)
  // ==========================================
  {
    id: 'tt-portofspain',
    name: 'पोर्ट ऑफ स्पेन (Port of Spain)',
    nameHi: 'पोर्ट ऑफ स्पेन',
    nameEn: 'Port of Spain',
    country: 'त्रिनिदाद',
    countryEn: 'Trinidad and Tobago',
    countryCode: 'TT',
    flag: '🇹🇹',
    region: 'त्रिनिदाद',
    regionEn: 'Trinidad',
    latitude: 10.6596,
    longitude: -61.5036,
    timezone: 'America/Port_of_Spain',
    timezoneHours: -4,
    type: 'capital',
  },
  {
    id: 'gy-georgetown',
    name: 'जॉर्जटाउन (Georgetown)',
    nameHi: 'जॉर्जटाउन',
    nameEn: 'Georgetown',
    country: 'गुयाना',
    countryEn: 'Guyana',
    countryCode: 'GY',
    flag: '🇬🇾',
    region: 'डेमेरारा-महाइका',
    regionEn: 'Demerara-Mahaica',
    latitude: 6.8013,
    longitude: -58.1551,
    timezone: 'America/Guyana',
    timezoneHours: -4,
    type: 'capital',
  },
  {
    id: 'sr-paramaribo',
    name: 'पारामारिबो (Paramaribo)',
    nameHi: 'पारामारिबो',
    nameEn: 'Paramaribo',
    country: 'सूरीनाम',
    countryEn: 'Suriname',
    countryCode: 'SR',
    flag: '🇸🇷',
    region: 'पारामारिबो जिला',
    regionEn: 'Paramaribo District',
    latitude: 5.852,
    longitude: -55.2038,
    timezone: 'America/Paramaribo',
    timezoneHours: -3,
    type: 'capital',
  },
  {
    id: 'ke-nairobi',
    name: 'नैरोबी (Nairobi)',
    nameHi: 'नैरोबी',
    nameEn: 'Nairobi',
    country: 'केन्या',
    countryEn: 'Kenya',
    countryCode: 'KE',
    flag: '🇰🇪',
    region: 'नैरोबी काउंटी',
    regionEn: 'Nairobi County',
    latitude: -1.2921,
    longitude: 36.8219,
    timezone: 'Africa/Nairobi',
    timezoneHours: 3,
    type: 'capital',
  },
  {
    id: 'ru-moscow',
    name: 'मॉस्को (Moscow)',
    nameHi: 'मॉस्को',
    nameEn: 'Moscow',
    country: 'रूस',
    countryEn: 'Russia',
    countryCode: 'RU',
    flag: '🇷🇺',
    region: 'केंद्रीय संघीय जिला',
    regionEn: 'Central Federal District',
    latitude: 55.7558,
    longitude: 37.6173,
    timezone: 'Europe/Moscow',
    timezoneHours: 3,
    type: 'capital',
  },
];

export function toSavedLocation(city: GlobalCity): SavedLocation {
  return {
    name: `${city.flag} ${city.nameHi} (${city.nameEn})`,
    latitude: city.latitude,
    longitude: city.longitude,
    state: city.region,
    country: city.country,
    type: city.type,
    timezone: city.timezone,
    timezoneHours: city.timezoneHours,
  };
}

export function searchGlobalCities(query: string, limit = 50): SavedLocation[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return GLOBAL_CITIES_DATABASE.slice(0, limit).map(toSavedLocation);
  }

  const matches = GLOBAL_CITIES_DATABASE.filter((city) => {
    return (
      city.name.toLowerCase().includes(q) ||
      city.nameHi.toLowerCase().includes(q) ||
      city.nameEn.toLowerCase().includes(q) ||
      city.country.toLowerCase().includes(q) ||
      city.countryEn.toLowerCase().includes(q) ||
      city.region.toLowerCase().includes(q) ||
      city.regionEn.toLowerCase().includes(q) ||
      city.countryCode.toLowerCase() === q
    );
  });

  return matches.slice(0, limit).map(toSavedLocation);
}

export function getCitiesByCountry(countryCode: string): SavedLocation[] {
  return GLOBAL_CITIES_DATABASE.filter((c) => c.countryCode === countryCode).map(toSavedLocation);
}

export function getPilgrimageCities(): SavedLocation[] {
  return GLOBAL_CITIES_DATABASE.filter((c) => c.type === 'pilgrimage').map(toSavedLocation);
}
