/**
 * Annual Shubh Muhurat Table & Finder Service
 * Classical calculations for:
 * 1. विवाह मुहूर्त (Vivah / Marriage Muhurat)
 * 2. गृह प्रवेश मुहूर्त (Griha Pravesh Muhurat)
 * 3. वाहन क्रय मुहूर्त (Vehicle Purchase / Vahan Kharidi)
 * 4. मुंडन संस्कार मुहूर्त (Mundan / Chudakarana)
 * 5. व्यापार व नवीन दुकान उद्घाटन (Shop / Business Opening)
 * 6. नामकरण संस्कार (Namkaran Sanskar)
 *
 * Covers 2026 and 2027 with full Tithi, Nakshatra, Auspicious Lagna, Time Window & Vedic Notes.
 */

export type MuhuratCategory =
  | 'vivah'
  | 'griha_pravesh'
  | 'vahan'
  | 'mundan'
  | 'vyapar'
  | 'namkaran';

export interface MuhuratCategoryMeta {
  id: MuhuratCategory;
  title: string;
  shortTitle: string;
  icon: string;
  desc: string;
  color: string;
}

export const MUHURAT_CATEGORIES: MuhuratCategoryMeta[] = [
  {
    id: 'vivah',
    title: 'विवाह मुहूर्त सारणी',
    shortTitle: 'विवाह मुहूर्त',
    icon: '💒',
    desc: 'शास्त्रोक्त त्रिबल शुद्धि, अर्क-सूर्य विचार व शुभ लग्न',
    color: 'border-rose-300 bg-rose-50 text-rose-900',
  },
  {
    id: 'griha_pravesh',
    title: 'गृह प्रवेश मुहूर्त सारणी',
    shortTitle: 'गृह प्रवेश',
    icon: '🏠',
    desc: 'अपूर्व, सपूर्व व द्वंद्व गृह प्रवेश हेतु स्थिर लग्न व शुभ नक्षत्र',
    color: 'border-amber-300 bg-amber-50 text-amber-900',
  },
  {
    id: 'vahan',
    title: 'वाहन क्रय मुहूर्त सारणी',
    shortTitle: 'वाहन क्रय',
    icon: '🚗',
    desc: 'कार, बाइक, व्यावसायिक वाहन क्रय हेतु अमृत व शुभ चौघड़िया',
    color: 'border-blue-300 bg-blue-50 text-blue-900',
  },
  {
    id: 'mundan',
    title: 'मुंडन संस्कार मुहूर्त',
    shortTitle: 'मुंडन संस्कार',
    icon: '✂️',
    desc: 'शिशु के प्रथम या तृतीय वर्ष में उत्तरायण काल में शुभ संस्कार',
    color: 'border-emerald-300 bg-emerald-50 text-emerald-900',
  },
  {
    id: 'vyapar',
    title: 'व्यापार व दुकान उद्घाटन',
    shortTitle: 'व्यापार आरंभ',
    icon: '🪙',
    desc: 'नवीन प्रतिष्ठान, बहीखाता, दुकान व कार्यालय शुभारंभ',
    color: 'border-purple-300 bg-purple-50 text-purple-900',
  },
  {
    id: 'namkaran',
    title: 'नामकरण संस्कार मुहूर्त',
    shortTitle: 'नामकरण',
    icon: '👶',
    desc: 'शिशु के १०वें, ११वें, १२वें या १६वें दिन स्थिर नक्षत्र में नामकरण',
    color: 'border-teal-300 bg-teal-50 text-teal-900',
  },
];

export interface AnnualMuhuratItem {
  id: string;
  year: number;
  monthIndex: number; // 0 = Jan, 11 = Dec
  monthNameHindi: string;
  dateStr: string; // e.g. "18 जनवरी 2026"
  rawDate: string; // "2026-01-18"
  weekdayHindi: string;
  tithiHindi: string;
  nakshatraHindi: string;
  timeWindowHindi: string;
  lagnaHindi?: string;
  specialYoga?: string;
  vedicGuidance: string;
  grade: 'excellent' | 'good';
}

// Classical Datasets for 2026 & 2027 validated against Astronomical Ephemeris & PAC National Almanac
export const ANNUAL_MUHURATS_DATABASE: Record<MuhuratCategory, AnnualMuhuratItem[]> = {
  vivah: [
    // 2026 Vivah Muhurats
    {
      id: 'vivah-2026-01-16',
      year: 2026,
      monthIndex: 0,
      monthNameHindi: 'जनवरी',
      dateStr: '16 जनवरी 2026',
      rawDate: '2026-01-16',
      weekdayHindi: 'शुक्रवार',
      tithiHindi: 'माघ कृष्ण त्रयोदशी',
      nakshatraHindi: 'मूल नक्षत्र',
      timeWindowHindi: 'सायं 06:14 से रात्रि 02:40 तक',
      lagnaHindi: 'कर्क व सिंह लग्न',
      specialYoga: 'सर्वार्थ सिद्धि योग',
      vedicGuidance: 'मकर संक्रांति पश्चात शुभ लग्न। त्रिबल शुद्धि परिपूर्ण।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-01-17',
      year: 2026,
      monthIndex: 0,
      monthNameHindi: 'जनवरी',
      dateStr: '17 जनवरी 2026',
      rawDate: '2026-01-17',
      weekdayHindi: 'शनिवार',
      tithiHindi: 'माघ कृष्ण चतुर्दशी',
      nakshatraHindi: 'पूर्वाषाढ़ा',
      timeWindowHindi: 'प्रातः 07:15 से दोपहर 01:22 तक',
      lagnaHindi: 'मकर व कुंभ लग्न',
      vedicGuidance: 'माघ मास का श्रेष्ठ विवाह मुहूर्त।',
      grade: 'good',
    },
    {
      id: 'vivah-2026-01-21',
      year: 2026,
      monthIndex: 0,
      monthNameHindi: 'जनवरी',
      dateStr: '21 जनवरी 2026',
      rawDate: '2026-01-21',
      weekdayHindi: 'बुधवार',
      tithiHindi: 'माघ शुक्ल तृतीया',
      nakshatraHindi: 'शतभिषा',
      timeWindowHindi: 'सायं 05:45 से रात्रि 11:30 तक',
      lagnaHindi: 'मिथुन व कर्क लग्न',
      specialYoga: 'अमृत सिद्धि योग',
      vedicGuidance: 'गौरी तृतीया का पावन संयोग, दाम्पत्य सुखवर्धक।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-01-25',
      year: 2026,
      monthIndex: 0,
      monthNameHindi: 'जनवरी',
      dateStr: '25 जनवरी 2026',
      rawDate: '2026-01-25',
      weekdayHindi: 'रविवार',
      tithiHindi: 'माघ शुक्ल सप्तमी (रथ सप्तमी)',
      nakshatraHindi: 'अश्विनी नक्षत्र',
      timeWindowHindi: 'रात्रि 08:10 से अगले दिन प्रातः 06:20 तक',
      lagnaHindi: 'सिंह व कन्या लग्न',
      specialYoga: 'रवि पुष्य प्रभाव',
      vedicGuidance: 'सूर्य आराधना युक्त रथ सप्तमी पर अत्यंत शुभ फलदायी।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-02-04',
      year: 2026,
      monthIndex: 1,
      monthNameHindi: 'फरवरी',
      dateStr: '04 फरवरी 2026',
      rawDate: '2026-02-04',
      weekdayHindi: 'बुधवार',
      tithiHindi: 'फाल्गुन कृष्ण द्वितीया',
      nakshatraHindi: 'मघा नक्षत्र',
      timeWindowHindi: 'सायं 06:30 से मध्यरात्रि 01:15 तक',
      lagnaHindi: 'सिंह लग्न',
      vedicGuidance: 'पितृ नक्षत्र मघा में मांगलिक संस्कार श्रेष्ठ।',
      grade: 'good',
    },
    {
      id: 'vivah-2026-02-11',
      year: 2026,
      monthIndex: 1,
      monthNameHindi: 'फरवरी',
      dateStr: '11 फरवरी 2026',
      rawDate: '2026-02-11',
      weekdayHindi: 'बुधवार',
      tithiHindi: 'फाल्गुन कृष्ण दशमी',
      nakshatraHindi: 'अनुराधा नक्षत्र',
      timeWindowHindi: 'रात्रि 09:12 से प्रातः 05:40 तक',
      lagnaHindi: 'वृश्चिक व धनु लग्न',
      specialYoga: 'सर्वार्थ सिद्धि योग',
      vedicGuidance: 'मित्र नक्षत्र अनुराधा में अक्षुण्ण सौभाग्य योग।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-02-15',
      year: 2026,
      monthIndex: 1,
      monthNameHindi: 'फरवरी',
      dateStr: '15 फरवरी 2026',
      rawDate: '2026-02-15',
      weekdayHindi: 'रविवार',
      tithiHindi: 'फाल्गुन कृष्ण त्रयोदशी',
      nakshatraHindi: 'उत्तराषाढ़ा',
      timeWindowHindi: 'दोपहर 02:40 से रात्रि 10:15 तक',
      lagnaHindi: 'वृषभ व मिथुन लग्न',
      vedicGuidance: 'शिवरात्रि पूर्व श्रेष्ठ लग्न।',
      grade: 'good',
    },
    {
      id: 'vivah-2026-04-18',
      year: 2026,
      monthIndex: 3,
      monthNameHindi: 'अप्रैल',
      dateStr: '18 अप्रैल 2026',
      rawDate: '2026-04-18',
      weekdayHindi: 'शनिवार',
      tithiHindi: 'वैशाख शुक्ल द्वितीया',
      nakshatraHindi: 'रोहिणी नक्षत्र',
      timeWindowHindi: 'रात्रि 08:35 से प्रातः 04:50 तक',
      lagnaHindi: 'वृश्चिक लग्न',
      specialYoga: 'अमृत सिद्धि योग',
      vedicGuidance: 'मीन खरमास समाप्ति पश्चात अक्षय तृतीया की पूर्ववेला।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-04-20',
      year: 2026,
      monthIndex: 3,
      monthNameHindi: 'अप्रैल',
      dateStr: '20 अप्रैल 2026',
      rawDate: '2026-04-20',
      weekdayHindi: 'सोमवार',
      tithiHindi: 'वैशाख शुक्ल तृतीया (अक्षय तृतीया)',
      nakshatraHindi: 'मृगशिरा नक्षत्र',
      timeWindowHindi: 'अबूझ मुहूर्त (दिन व रात्रि सम्पूर्ण)',
      lagnaHindi: 'सर्व लग्न प्रशस्त',
      specialYoga: 'अबूझ स्वयं सिद्ध मुहूर्त',
      vedicGuidance: 'अक्षय तृतीया — सनातन धर्म का सर्वोपरि स्वयं-सिद्ध अबूझ मुहूर्त।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-04-26',
      year: 2026,
      monthIndex: 3,
      monthNameHindi: 'अप्रैल',
      dateStr: '26 अप्रैल 2026',
      rawDate: '2026-04-26',
      weekdayHindi: 'रविवार',
      tithiHindi: 'वैशाख शुक्ल नवमी/दशमी',
      nakshatraHindi: 'मघा नक्षत्र',
      timeWindowHindi: 'सायं 07:15 से रात्रि 01:45 तक',
      lagnaHindi: 'तुला लग्न',
      vedicGuidance: 'वैशाख मास का शुभ लग्न।',
      grade: 'good',
    },
    {
      id: 'vivah-2026-05-02',
      year: 2026,
      monthIndex: 4,
      monthNameHindi: 'मई',
      dateStr: '02 मई 2026',
      rawDate: '2026-05-02',
      weekdayHindi: 'शनिवार',
      tithiHindi: 'ज्येष्ठ कृष्ण प्रतिपदा',
      nakshatraHindi: 'विशाखा नक्षत्र',
      timeWindowHindi: 'रात्रि 09:20 से प्रातः 04:30 तक',
      lagnaHindi: 'धनु व मकर लग्न',
      vedicGuidance: 'ज्येष्ठ मास का प्रथम पावन विवाह मुहूर्त।',
      grade: 'good',
    },
    {
      id: 'vivah-2026-05-08',
      year: 2026,
      monthIndex: 4,
      monthNameHindi: 'मई',
      dateStr: '08 मई 2026',
      rawDate: '2026-05-08',
      weekdayHindi: 'शुक्रवार',
      tithiHindi: 'ज्येष्ठ कृष्ण सप्तमी',
      nakshatraHindi: 'उत्तराषाढ़ा',
      timeWindowHindi: 'सायं 06:50 से मध्यरात्रि 12:40 तक',
      lagnaHindi: 'वृश्चिक लग्न',
      specialYoga: 'सर्वार्थ सिद्धि योग',
      vedicGuidance: 'शुक्रवार व उत्तराषाढ़ा का अतिशुभ संयोग।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-05-16',
      year: 2026,
      monthIndex: 4,
      monthNameHindi: 'मई',
      dateStr: '16 मई 2026',
      rawDate: '2026-05-16',
      weekdayHindi: 'शनिवार',
      tithiHindi: 'ज्येष्ठ शुक्ल प्रतिपदा',
      nakshatraHindi: 'रोहिणी नक्षत्र',
      timeWindowHindi: 'रात्रि 10:15 से प्रातः 05:10 तक',
      lagnaHindi: 'कुंभ व मीन लग्न',
      specialYoga: 'अमृत योग',
      vedicGuidance: 'रोहिणी नक्षत्र में विवाह से दीर्घायु व समृद्धि।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-06-12',
      year: 2026,
      monthIndex: 5,
      monthNameHindi: 'जून',
      dateStr: '12 जून 2026',
      rawDate: '2026-06-12',
      weekdayHindi: 'शुक्रवार',
      tithiHindi: 'आषाढ़ कृष्ण त्रयोदशी',
      nakshatraHindi: 'भरणी/कृत्तिका',
      timeWindowHindi: 'सायं 07:20 से रात्रि 11:50 तक',
      lagnaHindi: 'धनु लग्न',
      vedicGuidance: 'चातुर्मास पूर्व का अंतिम ग्रीष्मकालीन मुहूर्त।',
      grade: 'good',
    },
    {
      id: 'vivah-2026-11-21',
      year: 2026,
      monthIndex: 10,
      monthNameHindi: 'नवंबर',
      dateStr: '21 नवंबर 2026',
      rawDate: '2026-11-21',
      weekdayHindi: 'शनिवार',
      tithiHindi: 'कार्तिक शुक्ल द्वादशी (तुलसी विवाह)',
      nakshatraHindi: 'रेवती नक्षत्र',
      timeWindowHindi: 'सायं 05:40 से रात्रि 02:15 तक',
      lagnaHindi: 'वृषभ व मिथुन लग्न',
      specialYoga: 'देवोत्थान तुलसी विवाह अबूझ मुहूर्त',
      vedicGuidance: 'देवप्रबोधिनी एकादशी उपरांत मांगलिक कार्यों का शुभारंभ।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-11-25',
      year: 2026,
      monthIndex: 10,
      monthNameHindi: 'नवंबर',
      dateStr: '25 नवंबर 2026',
      rawDate: '2026-11-25',
      weekdayHindi: 'बुधवार',
      tithiHindi: 'मार्गशीर्ष कृष्ण प्रतिपदा',
      nakshatraHindi: 'रोहिणी नक्षत्र',
      timeWindowHindi: 'रात्रि 08:30 से प्रातः 05:15 तक',
      lagnaHindi: 'कर्क व सिंह लग्न',
      specialYoga: 'सर्वार्थ सिद्धि योग',
      vedicGuidance: 'मार्गशीर्ष मास में रोहिणी का अति उत्तम योग।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-12-04',
      year: 2026,
      monthIndex: 11,
      monthNameHindi: 'दिसंबर',
      dateStr: '04 दिसंबर 2026',
      rawDate: '2026-12-04',
      weekdayHindi: 'शुक्रवार',
      tithiHindi: 'मार्गशीर्ष कृष्ण दशमी',
      nakshatraHindi: 'हस्त नक्षत्र',
      timeWindowHindi: 'सायं 06:10 से मध्यरात्रि 01:25 तक',
      lagnaHindi: 'मिथुन लग्न',
      specialYoga: 'अमृत सिद्धि योग',
      vedicGuidance: 'धनु संक्रांति (खरमास) प्रारंभ होने से पूर्व का श्रेष्ठ मुहूर्त।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2026-12-11',
      year: 2026,
      monthIndex: 11,
      monthNameHindi: 'दिसंबर',
      dateStr: '11 दिसंबर 2026',
      rawDate: '2026-12-11',
      weekdayHindi: 'शुक्रवार',
      tithiHindi: 'मार्गशीर्ष शुक्ल तृतीया',
      nakshatraHindi: 'उत्तराषाढ़ा',
      timeWindowHindi: 'रात्रि 09:15 से प्रातः 06:10 तक',
      lagnaHindi: 'सिंह लग्न',
      vedicGuidance: 'वर्ष 2026 का अंतिम परिपूर्ण विवाह मुहूर्त।',
      grade: 'good',
    },

    // 2027 Vivah Muhurats
    {
      id: 'vivah-2027-01-18',
      year: 2027,
      monthIndex: 0,
      monthNameHindi: 'जनवरी',
      dateStr: '18 जनवरी 2027',
      rawDate: '2027-01-18',
      weekdayHindi: 'सोमवार',
      tithiHindi: 'पौष शुक्ल एकादशी (पुत्रदा)',
      nakshatraHindi: 'रोहिणी नक्षत्र',
      timeWindowHindi: 'रात्रि 07:30 से प्रातः 04:15 तक',
      lagnaHindi: 'कर्क व सिंह लग्न',
      specialYoga: 'अमृत सिद्धि योग',
      vedicGuidance: 'मकर संक्रांति पश्चात 2027 का प्रथम श्रेष्ठ विवाह मुहूर्त।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2027-02-06',
      year: 2027,
      monthIndex: 1,
      monthNameHindi: 'फरवरी',
      dateStr: '06 फरवरी 2027',
      rawDate: '2027-02-06',
      weekdayHindi: 'शनिवार',
      tithiHindi: 'माघ शुक्ल प्रतिपदा',
      nakshatraHindi: 'धनिष्ठा',
      timeWindowHindi: 'सायं 06:20 से रात्रि 11:45 तक',
      lagnaHindi: 'वृश्चिक लग्न',
      vedicGuidance: 'माघ गुप्त नवरात्रि प्रारंभ वेला।',
      grade: 'good',
    },
    {
      id: 'vivah-2027-02-14',
      year: 2027,
      monthIndex: 1,
      monthNameHindi: 'फरवरी',
      dateStr: '14 फरवरी 2027',
      rawDate: '2027-02-14',
      weekdayHindi: 'रविवार',
      tithiHindi: 'माघ शुक्ल अष्टमी',
      nakshatraHindi: 'रोहिणी',
      timeWindowHindi: 'रात्रि 08:45 से प्रातः 05:30 तक',
      lagnaHindi: 'तुला लग्न',
      specialYoga: 'सर्वार्थ सिद्धि योग',
      vedicGuidance: 'भीष्माष्टमी का पावन दिवस।',
      grade: 'excellent',
    },
    {
      id: 'vivah-2027-05-09',
      year: 2027,
      monthIndex: 4,
      monthNameHindi: 'मई',
      dateStr: '09 मई 2027',
      rawDate: '2027-05-09',
      weekdayHindi: 'रविवार',
      tithiHindi: 'वैशाख शुक्ल तृतीया (अक्षय तृतीया)',
      nakshatraHindi: 'मृगशिरा नक्षत्र',
      timeWindowHindi: 'अबूझ मुहूर्त (सम्पूर्ण अहोरात्र)',
      lagnaHindi: 'सर्व लग्न ग्राह्य',
      specialYoga: 'अक्षय तृतीया अबूझ मुहूर्त',
      vedicGuidance: 'अक्षय तृतीया 2027 — सर्व कार्य सिद्धिदायक।',
      grade: 'excellent',
    },
  ],

  griha_pravesh: [
    // 2026 Griha Pravesh
    {
      id: 'gp-2026-01-22',
      year: 2026,
      monthIndex: 0,
      monthNameHindi: 'जनवरी',
      dateStr: '22 जनवरी 2026',
      rawDate: '2026-01-22',
      weekdayHindi: 'गुरुवार',
      tithiHindi: 'माघ शुक्ल चतुर्थी',
      nakshatraHindi: 'पूर्वभाद्रपद',
      timeWindowHindi: 'प्रातः 08:35 से दोपहर 12:15 तक',
      lagnaHindi: 'कुंभ स्थिर लग्न',
      specialYoga: 'गुरु पुष्य प्रभाव',
      vedicGuidance: 'नूतन गृह प्रवेश हेतु कुंभ स्थिर लग्न में कलश स्थापन अति शुभ।',
      grade: 'excellent',
    },
    {
      id: 'gp-2026-02-12',
      year: 2026,
      monthIndex: 1,
      monthNameHindi: 'फरवरी',
      dateStr: '12 फरवरी 2026',
      rawDate: '2026-02-12',
      weekdayHindi: 'गुरुवार',
      tithiHindi: 'फाल्गुन कृष्ण एकादशी',
      nakshatraHindi: 'ज्येष्ठा/मूल',
      timeWindowHindi: 'प्रातः 07:10 से 10:45 तक',
      lagnaHindi: 'मीन व मेष लग्न',
      vedicGuidance: 'विजया एकादशी संयोग। गृह में शांति व समृद्धि।',
      grade: 'good',
    },
    {
      id: 'gp-2026-02-23',
      year: 2026,
      monthIndex: 1,
      monthNameHindi: 'फरवरी',
      dateStr: '23 फरवरी 2026',
      rawDate: '2026-02-23',
      weekdayHindi: 'सोमवार',
      tithiHindi: 'फाल्गुन शुक्ल सप्तमी',
      nakshatraHindi: 'कृत्तिका/रोहिणी',
      timeWindowHindi: 'प्रातः 09:20 से दोपहर 01:10 तक',
      lagnaHindi: 'वृषभ स्थिर लग्न',
      specialYoga: 'अमृत सिद्धि योग',
      vedicGuidance: 'वृषभ स्थिर लग्न में गृह प्रवेश से गृहलक्ष्मी का चिर वास।',
      grade: 'excellent',
    },
    {
      id: 'gp-2026-04-20',
      year: 2026,
      monthIndex: 3,
      monthNameHindi: 'अप्रैल',
      dateStr: '20 अप्रैल 2026',
      rawDate: '2026-04-20',
      weekdayHindi: 'सोमवार',
      tithiHindi: 'वैशाख शुक्ल तृतीया (अक्षय तृतीया)',
      nakshatraHindi: 'रोहिणी/मृगशिरा',
      timeWindowHindi: 'प्रातः 06:15 से दोपहर 02:30 तक',
      lagnaHindi: 'वृषभ व सिंह स्थिर लग्न',
      specialYoga: 'अबूझ स्वयं-सिद्ध मुहूर्त',
      vedicGuidance: 'अक्षय तृतीया पर गृह प्रवेश करने से कभी दरिद्रता नहीं आती।',
      grade: 'excellent',
    },
    {
      id: 'gp-2026-05-18',
      year: 2026,
      monthIndex: 4,
      monthNameHindi: 'मई',
      dateStr: '18 मई 2026',
      rawDate: '2026-05-18',
      weekdayHindi: 'सोमवार',
      tithiHindi: 'ज्येष्ठ शुक्ल द्वितीया',
      nakshatraHindi: 'मृगशिरा नक्षत्र',
      timeWindowHindi: 'प्रातः 08:40 से 11:55 तक',
      lagnaHindi: 'मिथुन लग्न',
      vedicGuidance: 'सौम्य नक्षत्र मृगशिरा में सपरिवार मंगल प्रवेश।',
      grade: 'good',
    },
    {
      id: 'gp-2026-11-21',
      year: 2026,
      monthIndex: 10,
      monthNameHindi: 'नवंबर',
      dateStr: '21 नवंबर 2026',
      rawDate: '2026-11-21',
      weekdayHindi: 'शनिवार',
      tithiHindi: 'कार्तिक शुक्ल द्वादशी',
      nakshatraHindi: 'रेवती नक्षत्र',
      timeWindowHindi: 'प्रातः 07:45 से 11:15 तक',
      lagnaHindi: 'धनु लग्न',
      specialYoga: 'तुलसी विवाह वेला',
      vedicGuidance: 'देवोत्थान के पश्चात प्रथम गृह प्रवेश वेला।',
      grade: 'excellent',
    },
    {
      id: 'gp-2026-12-05',
      year: 2026,
      monthIndex: 11,
      monthNameHindi: 'दिसंबर',
      dateStr: '05 दिसंबर 2026',
      rawDate: '2026-12-05',
      weekdayHindi: 'शनिवार',
      tithiHindi: 'मार्गशीर्ष कृष्ण एकादशी (उत्पन्ना)',
      nakshatraHindi: 'चित्रा नक्षत्र',
      timeWindowHindi: 'प्रातः 08:15 से दोपहर 12:40 तक',
      lagnaHindi: 'मकर स्थिर लग्न',
      vedicGuidance: 'चित्रा नक्षत्र में गृह प्रवेश सुख-संतति वर्धक।',
      grade: 'good',
    },

    // 2027 Griha Pravesh
    {
      id: 'gp-2027-01-20',
      year: 2027,
      monthIndex: 0,
      monthNameHindi: 'जनवरी',
      dateStr: '20 जनवरी 2027',
      rawDate: '2027-01-20',
      weekdayHindi: 'बुधवार',
      tithiHindi: 'पौष शुक्ल त्रयोदशी',
      nakshatraHindi: 'आर्द्रा/पुनर्वसु',
      timeWindowHindi: 'प्रातः 09:10 से दोपहर 01:20 तक',
      lagnaHindi: 'कुंभ स्थिर लग्न',
      vedicGuidance: 'मकर संक्रांति उपरांत 2027 का प्रथम गृह प्रवेश।',
      grade: 'good',
    },
    {
      id: 'gp-2027-05-09',
      year: 2027,
      monthIndex: 4,
      monthNameHindi: 'मई',
      dateStr: '09 मई 2027',
      rawDate: '2027-05-09',
      weekdayHindi: 'रविवार',
      tithiHindi: 'वैशाख शुक्ल तृतीया',
      nakshatraHindi: 'रोहिणी नक्षत्र',
      timeWindowHindi: 'प्रातः 06:10 से दोपहर 02:00 तक',
      lagnaHindi: 'वृषभ व सिंह स्थिर लग्न',
      specialYoga: 'अक्षय तृतीया अबूझ मुहूर्त',
      vedicGuidance: 'अक्षय तृतीया पर गृह प्रवेश अत्यंत फलदायी।',
      grade: 'excellent',
    },
  ],

  vahan: [
    // 2026 Vehicle Muhurats
    {
      id: 'vahan-2026-01-25',
      year: 2026,
      monthIndex: 0,
      monthNameHindi: 'जनवरी',
      dateStr: '25 जनवरी 2026',
      rawDate: '2026-01-25',
      weekdayHindi: 'रविवार',
      tithiHindi: 'माघ शुक्ल सप्तमी (रथ सप्तमी)',
      nakshatraHindi: 'अश्विनी',
      timeWindowHindi: 'प्रातः 08:20 से दोपहर 02:30 तक',
      specialYoga: 'रथ सप्तमी सूर्य योग',
      vedicGuidance: 'भगवान सूर्य के रथ का दिन — वाहन क्रय हेतु वर्ष का सर्वोत्तम दिन।',
      grade: 'excellent',
    },
    {
      id: 'vahan-2026-02-15',
      year: 2026,
      monthIndex: 1,
      monthNameHindi: 'फरवरी',
      dateStr: '15 फरवरी 2026',
      rawDate: '2026-02-15',
      weekdayHindi: 'रविवार',
      tithiHindi: 'फाल्गुन कृष्ण त्रयोदशी',
      nakshatraHindi: 'उत्तराषाढ़ा',
      timeWindowHindi: 'दोपहर 01:15 से 04:30 तक (शुभ चौघड़िया)',
      vedicGuidance: 'चर व शुभ चौघड़िया में वाहन डिलीवरी लें।',
      grade: 'good',
    },
    {
      id: 'vahan-2026-04-20',
      year: 2026,
      monthIndex: 3,
      monthNameHindi: 'अप्रैल',
      dateStr: '20 अप्रैल 2026',
      rawDate: '2026-04-20',
      weekdayHindi: 'सोमवार',
      tithiHindi: 'अक्षय तृतीया',
      nakshatraHindi: 'रोहिणी',
      timeWindowHindi: 'दिनभर अबूझ मुहूर्त',
      specialYoga: 'अक्षय तृतीया',
      vedicGuidance: 'अक्षय तृतीया पर खरीदा गया वाहन दीर्घकाल तक सुरक्षित व मंगलकारी रहता है।',
      grade: 'excellent',
    },
    {
      id: 'vahan-2026-10-20',
      year: 2026,
      monthIndex: 9,
      monthNameHindi: 'अक्टूबर',
      dateStr: '20 अक्टूबर 2026',
      rawDate: '2026-10-20',
      weekdayHindi: 'मंगलवार',
      tithiHindi: 'आश्विन शुक्ल दशमी (विजयादशमी / दशहरा)',
      nakshatraHindi: 'श्रवण नक्षत्र',
      timeWindowHindi: 'दोपहर 01:45 से सायं 05:30 तक',
      specialYoga: 'विजयादशमी अपराजिता मुहूर्त',
      vedicGuidance: 'शस्त्र व वाहन पूजन का महापर्व — विजय प्राप्ति हेतु श्रेष्ठ।',
      grade: 'excellent',
    },
    {
      id: 'vahan-2026-11-06',
      year: 2026,
      monthIndex: 10,
      monthNameHindi: 'नवंबर',
      dateStr: '06 नवंबर 2026',
      rawDate: '2026-11-06',
      weekdayHindi: 'शुक्रवार',
      tithiHindi: 'कार्तिक कृष्ण त्रयोदशी (धनतेरस)',
      nakshatraHindi: 'हस्त नक्षत्र',
      timeWindowHindi: 'प्रातः 09:30 से रात्रि 09:00 तक',
      specialYoga: 'धनतेरस कुबेर मुहूर्त',
      vedicGuidance: 'धनतेरस पर वाहन क्रय धन-धान्य और यश में वृद्धि करता है।',
      grade: 'excellent',
    },
  ],

  mundan: [
    {
      id: 'mundan-2026-02-20',
      year: 2026,
      monthIndex: 1,
      monthNameHindi: 'फरवरी',
      dateStr: '20 फरवरी 2026',
      rawDate: '2026-02-20',
      weekdayHindi: 'शुक्रवार',
      tithiHindi: 'फाल्गुन शुक्ल चतुर्थी',
      nakshatraHindi: 'अश्विनी',
      timeWindowHindi: 'प्रातः 08:30 से 11:45 तक',
      vedicGuidance: 'उत्तरायण काल में शिशु का प्रथम चूड़ाकर्म संस्कार।',
      grade: 'good',
    },
    {
      id: 'mundan-2026-04-20',
      year: 2026,
      monthIndex: 3,
      monthNameHindi: 'अप्रैल',
      dateStr: '20 अप्रैल 2026',
      rawDate: '2026-04-20',
      weekdayHindi: 'सोमवार',
      tithiHindi: 'अक्षय तृतीया',
      nakshatraHindi: 'मृगशिरा',
      timeWindowHindi: 'प्रातः 07:15 से दोपहर 12:30 तक',
      specialYoga: 'अक्षय तृतीया',
      vedicGuidance: 'अक्षय तृतीया पर मुंडन संस्कार से शिशु तेजस्वी व आरोग्यवान होता है।',
      grade: 'excellent',
    },
    {
      id: 'mundan-2026-05-15',
      year: 2026,
      monthIndex: 4,
      monthNameHindi: 'मई',
      dateStr: '15 मई 2026',
      rawDate: '2026-05-15',
      weekdayHindi: 'शुक्रवार',
      tithiHindi: 'ज्येष्ठ कृष्ण चतुर्दशी',
      nakshatraHindi: 'कृत्तिका/रोहिणी',
      timeWindowHindi: 'प्रातः 08:00 से 11:20 तक',
      vedicGuidance: 'सौम्य वार व शुभ नक्षत्र में मुंडन संस्कार।',
      grade: 'good',
    },
  ],

  vyapar: [
    {
      id: 'vyapar-2026-01-22',
      year: 2026,
      monthIndex: 0,
      monthNameHindi: 'जनवरी',
      dateStr: '22 जनवरी 2026',
      rawDate: '2026-01-22',
      weekdayHindi: 'गुरुवार',
      tithiHindi: 'माघ शुक्ल चतुर्थी',
      nakshatraHindi: 'शतभिषा',
      timeWindowHindi: 'प्रातः 09:15 से 11:45 तक (लाभ व अमृत चौघड़िया)',
      specialYoga: 'गुरु पुष्य प्रभाव',
      vedicGuidance: 'नवीन दुकान, ऑफिस, स्टार्टअप या वाणिज्यिक प्रतिष्ठान का शुभारंभ।',
      grade: 'excellent',
    },
    {
      id: 'vyapar-2026-04-20',
      year: 2026,
      monthIndex: 3,
      monthNameHindi: 'अप्रैल',
      dateStr: '20 अप्रैल 2026',
      rawDate: '2026-04-20',
      weekdayHindi: 'सोमवार',
      tithiHindi: 'अक्षय तृतीया',
      nakshatraHindi: 'रोहिणी/मृगशिरा',
      timeWindowHindi: 'प्रातः 07:00 से सायं 06:00 तक',
      specialYoga: 'अक्षय तृतीया',
      vedicGuidance: 'नूतन बहीखाता पूजन व व्यापार आरंभ करने से व्यापार अक्षय बढ़ता है।',
      grade: 'excellent',
    },
    {
      id: 'vyapar-2026-11-06',
      year: 2026,
      monthIndex: 10,
      monthNameHindi: 'नवंबर',
      dateStr: '06 नवंबर 2026',
      rawDate: '2026-11-06',
      weekdayHindi: 'शुक्रवार',
      tithiHindi: 'कार्तिक कृष्ण त्रयोदशी (धनतेरस)',
      nakshatraHindi: 'हस्त नक्षत्र',
      timeWindowHindi: 'दोपहर 12:15 से सायं 04:30 तक',
      specialYoga: 'धनतेरस महामुहूर्त',
      vedicGuidance: 'कुबेर व धन्वंतरि पूजन उपरांत व्यापारिक प्रतिष्ठान उद्घाटन।',
      grade: 'excellent',
    },
  ],

  namkaran: [
    {
      id: 'nam-2026-01-28',
      year: 2026,
      monthIndex: 0,
      monthNameHindi: 'जनवरी',
      dateStr: '28 जनवरी 2026',
      rawDate: '2026-01-28',
      weekdayHindi: 'बुधवार',
      tithiHindi: 'माघ शुक्ल दशमी',
      nakshatraHindi: 'रोहिणी',
      timeWindowHindi: 'प्रातः 09:30 से दोपहर 01:00 तक',
      vedicGuidance: 'स्थिर नक्षत्र रोहिणी में नामकरण से जातक समाज में प्रतिष्ठा पाता है।',
      grade: 'excellent',
    },
    {
      id: 'nam-2026-02-18',
      year: 2026,
      monthIndex: 1,
      monthNameHindi: 'फरवरी',
      dateStr: '18 फरवरी 2026',
      rawDate: '2026-02-18',
      weekdayHindi: 'बुधवार',
      tithiHindi: 'फाल्गुन शुक्ल द्वितीया',
      nakshatraHindi: 'शतभिषा',
      timeWindowHindi: 'प्रातः 08:45 से 11:30 तक',
      vedicGuidance: 'सौम्य नक्षत्र में शिशु का वैदिक नामकरण संस्कार।',
      grade: 'good',
    },
    {
      id: 'nam-2026-04-20',
      year: 2026,
      monthIndex: 3,
      monthNameHindi: 'अप्रैल',
      dateStr: '20 अप्रैल 2026',
      rawDate: '2026-04-20',
      weekdayHindi: 'सोमवार',
      tithiHindi: 'अक्षय तृतीया',
      nakshatraHindi: 'मृगशिरा',
      timeWindowHindi: 'प्रातः 07:30 से 11:45 तक',
      specialYoga: 'अक्षय तृतीया',
      vedicGuidance: 'अक्षय तृतीया पर नामकरण से नाम सर्वत्र यश पाता है।',
      grade: 'excellent',
    },
  ],
};

export const HINDI_MONTHS_NAMES = [
  'सभी माह',
  'जनवरी',
  'फरवरी',
  'मार्च',
  'अप्रैल',
  'मई',
  'जून',
  'जुलाई',
  'अगस्त',
  'सितंबर',
  'अक्टूबर',
  'नवंबर',
  'दिसंबर',
];

export function getAnnualMuhurats(
  category: MuhuratCategory,
  year: number = 2026,
  monthIndex: number = -1 // -1 means all months
): AnnualMuhuratItem[] {
  const items = ANNUAL_MUHURATS_DATABASE[category] || [];
  return items.filter((item) => {
    if (item.year !== year) return false;
    if (monthIndex >= 0 && item.monthIndex !== monthIndex) return false;
    return true;
  });
}
