import {
  Sun,
  Calendar,
  Clock,
  Compass,
  User,
  Heart,
  Gift,
  Bell,
  Sparkles,
  Timer,
  BookOpen,
  Home,
  Flame,
  Star,
  type LucideIcon,
} from 'lucide-react';

export interface BookPageItem {
  id: string;
  title: string;
  label: string;
  pageNumber: number;
  chapter: string;
  desc: string;
  icon: LucideIcon;
  screenTitle?: string;
}

/** Physical flip-book chapters */
export const FLIP_BOOK_CHAPTERS: BookPageItem[] = [
  {
    id: 'panchang',
    title: 'पंचांग',
    label: 'पंचांग',
    pageNumber: 1,
    chapter: '',
    desc: 'तिथि • नक्षत्र • योग • करण • सूर्य समय',
    icon: Calendar,
    screenTitle: '📜 पूरा पंचांग',
  },
  {
    id: 'rashifal',
    title: 'दैनिक राशिफल',
    label: 'राशिफल',
    pageNumber: 2,
    chapter: '',
    desc: 'मेष से मीन राशि का दैनिक गोचर फल व उपाय',
    icon: Star,
    screenTitle: '🌟 दैनिक राशिफल',
  },
  {
    id: 'kundali',
    title: 'कुंडली',
    label: 'कुंडली',
    pageNumber: 3,
    chapter: '',
    desc: 'जन्म कुंडली • वर्ग • दशा • फलित',
    icon: Sparkles,
    screenTitle: '🪐 जन्म कुंडली',
  },
  {
    id: 'muhurat',
    title: 'शुभ मुहूर्त',
    label: 'शुभ मुहूर्त',
    pageNumber: 4,
    chapter: '',
    desc: 'विवाह • गृहप्रवेश • कार्यारम्भ',
    icon: Clock,
    screenTitle: '🙏 काम के अनुसार मुहूर्त',
  },
  {
    id: 'choghadiya',
    title: 'शुभ समय',
    label: 'शुभ समय',
    pageNumber: 5,
    chapter: '',
    desc: 'चौघड़िया • राहुकाल • यमगण्ड • गुलिक',
    icon: Timer,
    screenTitle: '✨ शुभ समय सलाह',
  },
  {
    id: 'durga',
    title: 'दुर्गा सप्तशती',
    label: 'दुर्गा सप्तशती',
    pageNumber: 6,
    chapter: '',
    desc: '१३ सम्पूर्ण अध्याय, कवच, अर्गला, कीलक व कुंजिका',
    icon: Flame,
    screenTitle: '🔱 श्री दुर्गा सप्तशती',
  },
  {
    id: 'upay',
    title: 'चमत्कारी उपाय',
    label: 'ग्रह उपाय',
    pageNumber: 7,
    chapter: '',
    desc: 'कुंडली अनुसार ग्रह शांति, लाल किताब व चमत्कारी टोटके',
    icon: Sparkles,
    screenTitle: '🔮 ग्रह शांति व चमत्कारी उपाय',
  },
  {
    id: 'vastu',
    title: 'वास्तु शास्त्र',
    label: 'वास्तु',
    pageNumber: 8,
    chapter: '',
    desc: '८ दिशाएं, गृह निर्माण नियम व बिना तोड़-फोड़ के टिप्स',
    icon: Home,
    screenTitle: '🏡 वैदिक वास्तु शास्त्र',
  },
  {
    id: 'gita',
    title: 'गीता ज्ञान',
    label: 'गीता ज्ञान',
    pageNumber: 9,
    chapter: '',
    desc: 'श्रीमद्भगवद्गीता श्लोक ऑफ़ द डे व दिव्य उपदेश',
    icon: BookOpen,
    screenTitle: '📜 श्रीमद्भगवद्गीता ज्ञान',
  },
  {
    id: 'yatra',
    title: 'यात्रा',
    label: 'यात्रा',
    pageNumber: 10,
    chapter: '',
    desc: 'दिशाशूल • शुभ दिशा • यात्रा सलाह',
    icon: Compass,
    screenTitle: '🚗 यात्रा मुहूर्त',
  },
  {
    id: 'milan',
    title: 'कुंडली मिलान',
    label: 'मिलान',
    pageNumber: 11,
    chapter: '',
    desc: '३६ गुण मिलान • नाड़ी • भकूट दोष व PDF',
    icon: Heart,
    screenTitle: '💍 अष्टकूट मिलान व PDF',
  },
  {
    id: 'festivals',
    title: 'व्रत एवं त्योहार',
    label: 'व्रत एवं त्योहार',
    pageNumber: 12,
    chapter: '',
    desc: 'एकादशी • पूर्णिमा • अमावस्या • पर्व',
    icon: Gift,
    screenTitle: '📅 पर्व और व्रत',
  },
  {
    id: 'vratkatha',
    title: 'व्रत कथा व आरती',
    label: 'व्रत कथा',
    pageNumber: 13,
    chapter: '',
    desc: 'एकादशी, प्रदोष, सत्यनारायण कथा व आरती संग्रह',
    icon: BookOpen,
    screenTitle: '📖 व्रत कथा एवं आरती संग्रह',
  },
  {
    id: 'reminders',
    title: 'रिमाइंडर',
    label: 'रिमाइंडर',
    pageNumber: 14,
    chapter: '',
    desc: 'व्रत और शुभ समय के लिए धार्मिक सूचनाएँ',
    icon: Bell,
    screenTitle: '🔔 उमा Reminder',
  },
];

export const BOOK_PAGES: BookPageItem[] = [
  {
    id: 'panchang',
    title: 'दैनिक पंचांग व काल गणना',
    label: 'पंचांग',
    pageNumber: 1,
    chapter: 'प्रथम अध्याय',
    desc: 'तिथि, वार, नक्षत्र, योग, करण व अयनांश',
    icon: Sun,
    screenTitle: '📜 पूरा पंचांग',
  },
  {
    id: 'rashifal',
    title: 'दैनिक राशिफल (मेष से मीन)',
    label: 'राशिफल',
    pageNumber: 2,
    chapter: 'द्वितीय अध्याय',
    desc: 'सभी १२ राशियों का दैनिक गोचर फल, शुभ रंग, अंक व उपाय',
    icon: Star,
    screenTitle: '🌟 दैनिक राशिफल',
  },
  {
    id: 'choghadiya',
    title: 'चौघड़िया चक्र व मुहूर्त वेला',
    label: 'चौघड़िया',
    pageNumber: 3,
    chapter: 'तृतीय अध्याय',
    desc: 'दिन व रात्रि के अमृत, शुभ, लाभ व त्याज्य काल',
    icon: Clock,
    screenTitle: '✨ शुभ समय सलाह',
  },
  {
    id: 'kundali',
    title: 'जातक जन्म पत्रिका व विंशोत्तरी दशा',
    label: 'कुंडली',
    pageNumber: 4,
    chapter: 'चतुर्थ अध्याय',
    desc: 'लग्न चक्र, षोडश वर्ग, महादशा व फलादेश',
    icon: User,
    screenTitle: '🪐 जन्म कुंडली',
  },
  {
    id: 'durga',
    title: 'श्री दुर्गा सप्तशती सम्पूर्ण पाठ',
    label: 'दुर्गा सप्तशती',
    pageNumber: 5,
    chapter: 'पंचम अध्याय',
    desc: '१३ अध्याय, कवच, अर्गला, कीलक, सिद्ध कुंजिका व आरती',
    icon: Flame,
    screenTitle: '🔱 श्री दुर्गा सप्तशती सम्पूर्ण',
  },
  {
    id: 'upay',
    title: 'ग्रह शांति, लाल किताब व चमत्कारी उपाय',
    label: 'चमत्कारी उपाय',
    pageNumber: 6,
    chapter: 'षष्ठ अध्याय',
    desc: 'कुंडली के अनुसार ग्रह शांति, लाल किताब व तात्कालिक टोटके',
    icon: Sparkles,
    screenTitle: '🔮 ग्रह शांति व चमत्कारी उपाय',
  },
  {
    id: 'vastu',
    title: 'वैदिक वास्तु शास्त्र व चमत्कारी टिप्स',
    label: 'वास्तु शास्त्र',
    pageNumber: 7,
    chapter: 'सप्तम अध्याय',
    desc: '८ दिशाएं, गृह निर्माण नियम व बिना तोड़-फोड़ के उपाय',
    icon: Home,
    screenTitle: '🏡 वैदिक वास्तु शास्त्र',
  },
  {
    id: 'gita',
    title: 'श्रीमद्भगवद्गीता श्लोक ऑफ़ द डे',
    label: 'गीता ज्ञान',
    pageNumber: 8,
    chapter: 'अष्टम अध्याय',
    desc: 'दिव्य श्लोक, हिंदी भावार्थ व जीवन दर्शन',
    icon: BookOpen,
    screenTitle: '📜 श्रीमद्भगवद्गीता ज्ञान',
  },
  {
    id: 'muhurat',
    title: 'कार्य सिद्धि व शुभ मुहूर्त निर्णय',
    label: 'मुहूर्त',
    pageNumber: 9,
    chapter: 'नवम अध्याय',
    desc: 'विवाह, गृह प्रवेश, व्यापार, वाहन व नामकरण मुहूर्त',
    icon: Compass,
    screenTitle: '🙏 काम के अनुसार मुहूर्त',
  },
  {
    id: 'yatra',
    title: 'दिशाशूल विचार व यात्रा शुद्धि',
    label: 'यात्रा',
    pageNumber: 10,
    chapter: 'दशम अध्याय',
    desc: 'दैनिक दिशाशूल, यात्रा दूरी व शास्त्रोक्त सात्विक परिहार',
    icon: Compass,
    screenTitle: '🚗 यात्रा मुहूर्त',
  },
  {
    id: 'milan',
    title: 'अष्टकूट मिलान व वर-कन्या मेलापक (PDF)',
    label: 'मिलान',
    pageNumber: 11,
    chapter: 'एकादश अध्याय',
    desc: '36 गुण विचार, नाड़ी, भकूट, गण, योनि व PDF रिपोर्ट डाउनलोड',
    icon: Heart,
    screenTitle: 'कुंडली मिलान – 36 गुण व PDF',
  },
  {
    id: 'festivals',
    title: 'सनातन व्रत, पर्व व राष्ट्रीय उत्सव',
    label: 'व्रत/त्योहार',
    pageNumber: 12,
    chapter: 'द्वादश अध्याय',
    desc: 'एकादशी, प्रदोष, पूर्णिमा, अमावस्या, शिवरात्रि व समस्त व्रत',
    icon: Gift,
    screenTitle: '📅 पर्व और व्रत',
  },
  {
    id: 'vratkatha',
    title: 'व्रत कथा, पूजा विधि व आरती संग्रह',
    label: 'व्रत कथा',
    pageNumber: 13,
    chapter: 'त्रयोदश अध्याय',
    desc: 'एकादशी, प्रदोष, सत्यनारायण सम्पूर्ण कथा, स्तोत्र व आरती',
    icon: BookOpen,
    screenTitle: '📖 व्रत कथा एवं आरती संग्रह',
  },
  {
    id: 'reminders',
    title: 'वैदिक अनुष्ठान व धार्मिक संकल्प',
    label: 'रिमाइंडर',
    pageNumber: 14,
    chapter: 'चतुर्दश अध्याय',
    desc: 'नित्य पूजा, जप, साधना व व्यक्तिगत धार्मिक संकल्प स्मरण',
    icon: Bell,
    screenTitle: '🔔 उमा Reminder',
  },
];
